[package]
name = "solo-tui"
version.workspace = true
publish = false
description = "Solo-tui for Sova"
authors = ["Tanguy Dubois <dubois.tanguy@gmail.com>"]
license = "MIT"
edition = "2024"

[features]
default = []
asio = ["doux-sova/asio", "sova_server/asio"]

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
sova_core = { path = "../core", package = "core" }
sova_server = { path = "../server", package = "sova-server", features = ["audio"] }
langs = { path = "../langs" }
crossbeam-channel = { workspace = true }
tui-textarea = "0.7.0"
arboard = { version = "3.6.1", features = ["wayland-data-control"] }
serde_json = { workspace = true }
doux-sova = { git = "https://github.com/sova-org/doux", tag = "v0.0.32", package = "doux-sova" }
