[workspace]
members = [
    "core",
    "desktop",
    "langs",
    "server",
    "sova-tui",
]
resolver = "3"

[workspace.package]
version = "0.1.1"

[workspace.dependencies]
crossbeam-channel = "0.5.17"
loro = "=1.12.0"
pest = "2.9.1"
pest_derive = "2.9.1"
rand = "0.10.2"
serde_json = "1.0.151"
thread-priority = "3.1.1"
tokio = "1.53.1"

[workspace.dependencies.lalrpop-util]
version = "0.23.1"
features = [
    "lexer",
    "unicode",
]

[workspace.dependencies.serde]
version = "1.0.229"
features = ["derive"]

[profile.dev]
opt-level = 0

[profile.dev.package.core]
opt-level = 2

[profile.dev.package.doux-sova]
opt-level = 2

[profile.dev.package.langs]
opt-level = 2

[profile.dev.package."*"]
opt-level = 2

[profile.profiling]
debug = 2
inherits = "release"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "unwind"
strip = true

[patch."https://github.com/sova-org/sova".core]
path = "core"
