[workspace]
members = [
    "core",
    "langs",
    "server",
    "solo-tui",
    "desktop",
]
resolver = "3"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "unwind"
strip = true

[profile.dev]
opt-level = 3

[profile.profiling]
inherits = "release"
debug = true

[patch."https://github.com/sova-org/sova"]
core = { path = "core" }
