[workspace]
members = [
    "core",
    "langs",
    "server",
    "solo-tui",
    "desktop",
]
resolver = "3"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "unwind"
strip = true

[profile.dev]
opt-level = 0

[profile.dev.package.core]
opt-level = 2

[profile.dev.package.doux-sova]
opt-level = 2

[profile.profiling]
inherits = "release"
debug = true

[patch."https://github.com/sova-org/sova"]
core = { path = "core" }

[patch."https://github.com/sova-org/doux"]
doux-sova = { path = "/Users/bubo/doux/doux-sova" }
doux = { path = "/Users/bubo/doux" }
