[package]
name = "langs"
version.workspace = true
edition = "2024"
publish = false

[build-dependencies]
lalrpop = "0.22.1"

[features]
rhai = ["dep:rhai"]
lua = ["dep:mlua"]

[dependencies]
sova_core = { path = "../core", package = "core" }
lalrpop-util = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }
rhai = { version = "1.23.6", features = ["internals", "no_module", "no_time"], optional = true }
mlua = { version = "0.11.5", features = ["luau"], optional = true }
rand = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true }

[dev-dependencies]
rusty_link = "0.4.4"
regex = "1"
