[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
midir = "0.10.1"
rosc = "0.10.1"
rusty_link = "0.4.4"
thread-priority = { workspace = true }
audio_thread_priority = "0.32"
lalrpop-util = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true }
toml = "0.8.0"
rand = { workspace = true }
simple-easing = "1.0.1"
crossbeam-channel = { workspace = true }
dirs = "5.0"
pest = { workspace = true }
pest_derive = { workspace = true }
rand_chacha = "0.9.0"
tokio = { workspace = true, features = ["sync"] }

[lib]
name = "sova_core"
path = "src/lib.rs"

[dev-dependencies]
tempfile = "3.0"
