WHITESPACE = _{ " " | "\t" | NEWLINE }
COMMENT = _{ "//" ~ (!NEWLINE ~ ANY)* }

letter = _{ ASCII_ALPHA }
digit = _{ ASCII_DIGIT }
int = @{ digit+ }
op = { 
	"+" | 
    "-" | 
    "*" | 
    "/" | 
    "%" | 
    "<" | 
    ">" |
    "=" |
    "!"
}

seq_var = { "$" }
line_qualif = { "l_" }
frame_qualif = { "f_" }
env_func = { "_" }
qualif = _{ (seq_var ~ (line_qualif | frame_qualif)?) | env_func }
quote = { "'" }
name = @{ (letter | digit | op | quote)+ }
ident = ${ !note ~ qualif? ~ name }

note_letter = { 'A'..'G' | 'a'..'g' }
sharp = { "#" }
flat = { "b" }
note = ${ note_letter ~ (sharp | flat)* ~ int? ~ !letter }

real = @{ int? ~ "." ~ int }
number = _{ real | int }
micros = ${ int ~ "u" } 
semibeats = ${ number ~ "''" } 
beats = ${ number ~ "'" } 
frames = ${ number ~ "f" }
duration = _{ micros | semibeats | beats | frames }

str = @{ 
	("\"" ~ (!"\"" ~ ANY)* ~ "\"") |
    ("'" ~ (!"'" ~ ANY)* ~ "'") 
}

atom = _{ duration | number | str | note | ident }
list = { "(" ~ expression* ~ ")" }
expression = _{ list | atom }

prog = _{ SOI ~ expression* ~ EOI }

