[package]
name = "sova-server"
version = "0.1.0"
edition = "2024"

[lib]
name = "sova_server"
path = "src/lib.rs"

[[bin]]
name = "sova_server"
path = "src/main.rs"

[features]
default = ["audio", "soundfont"]
audio = ["dep:doux-sova"]
soundfont = ["audio", "doux-sova/soundfont"]

[dependencies]
sova_core = { path = "../core", package = "core" }
langs = { path = "../langs" }
tokio = { version = "1.44.1", features = ["full"] }
clap = { version = "4.5.34", features = ["derive"] }
thread-priority = "1.2.0"
serde = { version = "1.0.217", features = ["derive"] }
postcard = { version = "1", features = ["alloc"] }
crossbeam-channel = "0.5.15"
socket2 = "0.5"
doux-sova = { git = "https://github.com/sova-org/doux", tag = "v0.0.6", package = "doux-sova", optional = true }
