// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,loop:20, eucloop:20, binloop:20, spread:20, scatter:20, pick:20, with:20, withdirt:20, seq:20, for:20, if:20, def:20, note:20, prog:20, control:20, at:20, chanpress:20, osc:20, dirt:20, scale:20, clamp:20, min:20, max:20, quantize:20, sine:20, saw:20, triangle:20, isaw:20, randstep:20, ccin:20, not:20, lt:20, leq:20, gt:20, geq:20, "dev:":22, "ch:":22, "v:":22, "dur:":22, "sh:":22, "-n":22, "-r":22}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!dQVQPOOOtQPO'#C^OOQO'#Co'#CoOOQO'#Cd'#CdOOQO'#Cn'#CnOOQO'#Cj'#CjQVQPOOOOQO,58x,58xO{QPO,58xOOQO-E6h-E6hOOQO1G.d1G.d",
  stateData: "!S~OaOS~ORPOTSOUSOVSOXROYQOZQO[SO]SO~OSVO~PVOSYO~PVO",
  goto: "!RdPPePPPPPePPPPPkPPPu{XSOPUWQUOQWPTXUWXTOPUWXROPUW",
  nodeNames: "⚠ Program List ( ) String Number DirtParam Word Identifier Keyword ContextKeyword Operator Comment",
  maxTerm: 19,
  nodeProps: [
    ["group", 8,"Word"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: ")O~RnX^#Ppq#Pqr#trs$Puv#zvw%sxy%yyz&Oz{#z{|#z}!O#z!P!Q&T!Q![&]![!]&v!]!^'e!^!_'|!_!`#t!`!a(U!a!b#z!c!}(^#T#o(^#p#q(x#y#z#P$f$g#P#BY#BZ#P$IS$I_#P$I|$JO#P$JT$JU#P$KV$KW#P&FU&FV#P~#UYa~X^#Ppq#P#y#z#P$f$g#P#BY#BZ#P$IS$I_#P$I|$JO#P$JT$JU#P$KV$KW#P&FU&FV#P~#wP!_!`#z~$PO[~~$SWOY$PZr$Prs$ls#O$P#O#P$q#P;'S$P;'S;=`%m<%lO$P~$qOT~~$tRO;'S$P;'S;=`$};=`O$P~%QXOY$PZr$Prs$ls#O$P#O#P$q#P;'S$P;'S;=`%m;=`<%l$P<%lO$P~%pP;=`<%l$P~%vPvw#z~&OOR~~&TOS~~&YP[~!P!Q#z~&bQU~!O!P&h!Q![&]~&kP!Q![&n~&sPU~!Q![&n~&yQ!c!}'P#T#o'P~'UTV~}!O'P!Q!['P!c!}'P#R#S'P#T#o'P~'jS]~OY'eZ;'S'e;'S;=`'v<%lO'e~'yP;=`<%l'e~(RP[~!^!_#z~(ZP[~!`!a#z~(cVX~st(^}!O(^!Q![(^![!](^!c!}(^#R#S(^#T#o(^~({P#p#q#z",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 9, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
