// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  List = 2,
  String = 5,
  Number = 6,
  DirtParam = 7,
  Word = 8,
  Identifier = 9,
  Keyword = 10,
  ContextKeyword = 11,
  Operator = 12,
  Comment = 13
