// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,IF:6, ELSE:6, ELIF:6, WHILE:6, L:6, RANGE:6, DO:6, EACH:6, EVERY:6, FORK:6, SWITCH:6, CASE:6, DEFAULT:6, BREAK:6, PROB:6, EU:6, BIN:6, END:6, FUNC:8, FN:8, CALL:8, RETURN:8, PLAY:10, WAIT:10, DEV:10, BYTES:10, CHOOSE:12, ALT:12, SET:14, T:16, R:16, I:16, E:16, NEG:18, NOT:18, BNOT:18, ABS:18, RAND:18, TOSS:18, LEN:18, PICK:18, CYCLE:18, ADD:18, SUB:18, MUL:18, DIV:18, MOD:18, GT:18, LT:18, GTE:18, LTE:18, EQ:18, NE:18, AND:18, OR:18, XOR:18, BAND:18, BOR:18, BXOR:18, SHL:18, SHR:18, MIN:18, MAX:18, QT:18, RRAND:18, DRUNK:18, CLAMP:18, WRAP:18, SCALE:18, GET:18, MNEW:18, MGET:18, MSET:18, MHAS:18, MMERGE:18, MLEN:18, MAP:18, FILTER:18, REDUCE:18}
export const parser = LRParser.deserialize({
  version: 14,
  states: "nQVQPOOOOQO'#Cr'#CrOOQO'#Cn'#CnQVQPOOOOQO-E6l-E6l",
  stateData: "!a~OeOS~OQPORPOSPOTPOUPOVPOWPOXPOYPOZPO[PO]PO^PO_PO`POaPO~OZQ[`[~",
  goto: "rgPPPPPPPPPPPPPPPPPPhPPPnQRORSRTQOR",
  nodeNames: "⚠ Program Identifier ControlKeyword FunctionKeyword EventKeyword SelectionKeyword AssignKeyword BuiltinVar OperatorKeyword SymbolicOperator ScopedVar Symbol ListStart Number String Punctuation Comment",
  maxTerm: 22,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "+O~RvXY#iYZ#i]^#ipq#iqr#zrs$Xst%{uv$Svw&dwx&lxy&wyz&wz{$S{|$S}!O&|!P!Q$S!Q!['S![!]'m!]!^&w!^!_(a!_!`(l!`!a(u!a!b$S!b!c$S!c!h)Q!h!i)f!i!j)f!j!n)Q!n!o)f!o!})Q!}#O&w#P#Q&w#Q#R$S#T#o)Q#o#p&w#p#q*v#q#r&w#r#s$S~#nSe~XY#iYZ#i]^#ipq#i~$PPY~!_!`$S~$XOY~~$[WOY$XZr$Xrs$ts#O$X#O#P$y#P;'S$X;'S;=`%u<%lO$X~$yO_~~$|RO;'S$X;'S;=`%V;=`O$X~%YXOY$XZr$Xrs$ts#O$X#O#P$y#P;'S$X;'S;=`%u;=`<%l$X<%lO$X~%xP;=`<%l$X~&QSa~OY%{Z;'S%{;'S;=`&^<%lO%{~&aP;=`<%l%{~&iPY~vw$S~&oP!}#O&r~&wO]~~&|O`~~'PP!Q!['S~'XQ^~!O!P'_!Q!['S~'bP!Q!['e~'jP^~!Q!['e~'rQ`~!c!}'x#T#o'x~'}U[~st'x}!O'x!Q!['x!c!}'x#R#S'x#T#o'x~(fQY~!^!_$S!_!`$S~(oQ!_!`$S!`!a$S~(zQY~!_!`$S!`!a$S~)VTQ~!O!P)Q!Q![)Q!c!})Q#R#S)Q#T#o)Q~)kTQ~!O!P)z!Q![)Q!c!})Q#R#S)Q#T#o)Q~*PTQ~!O!P)Q!Q![)Q!c!}*`#R#S)Q#T#o*`~*gTZ~Q~!O!P)Q!Q![*`!c!}*`#R#S*`#T#o*`~*{PY~#p#q$S",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 2, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 57
})
