// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Identifier = 2,
  ControlKeyword = 3,
  FunctionKeyword = 4,
  EventKeyword = 5,
  SelectionKeyword = 6,
  AssignKeyword = 7,
  BuiltinVar = 8,
  OperatorKeyword = 9,
  SymbolicOperator = 10,
  ScopedVar = 11,
  Symbol = 12,
  ListStart = 13,
  Number = 14,
  String = 15,
  Punctuation = 16,
  Comment = 17
