// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "nQVQPOOOOQO'#Cd'#CdOOQO'#C`'#C`QVQPOOOOQO-E6^-E6^",
  stateData: "_~OVOS~OQPORPO~O",
  goto: "dXPPPPYPPP`QRORSRTQOR",
  nodeNames: "⚠ Program ControlKeyword Integer",
  maxTerm: 8,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "!Z~RWXYkYZk]^kpqk!Q![|!c!d!U!e!f!U!p!q!U~pSV~XYkYZk]^kpqk~!RPR~!Q![|~!ZOQ~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
