import type { Theme } from '../types';

export const bluescreen: Theme = {
  name: 'Blue Screen',
  colors: {
    background: '#0000aa',
    surface: '#0000cc',
    border: '#5555ff',
    text: '#ffffff',
    textSecondary: '#aaaaff',
    accent: '#ffffff',
    accentHover: '#ddddff',
    input: '#0000cc',
    inputBorder: '#5555ff',
    button: '#0000cc',
    buttonHover: '#0000ee',
    danger: '#ffffff',
    dangerHover: '#dddddd',
  },
  editor: {
    background: '#0000aa',
    foreground: '#ffffff',
    caret: '#ffffff',
    selection: '#0000ee',
    activeLine: '#0000cc',
    gutter: '#0000aa',
    gutterText: '#aaaaff',
    activeLineGutter: '#0000cc',
    lineNumber: '#aaaaff',
  },
  syntax: {
    keyword: '#ffffff',
    operator: '#ffffff',
    string: '#dddddd',
    number: '#ffffff',
    boolean: '#ffffff',
    comment: '#8888ff',
    function: '#ffffff',
    class: '#ffffff',
    variable: '#eeeeee',
    property: '#eeeeee',
    constant: '#ffffff',
    type: '#ffffff',
    tag: '#ffffff',
    attribute: '#eeeeee',
  },
  ansi: {
    black: '#000088',
    red: '#ffffff',
    green: '#ffffff',
    yellow: '#ffffff',
    blue: '#dddddd',
    magenta: '#ffffff',
    cyan: '#ffffff',
    white: '#ffffff',
    brightBlack: '#5555ff',
    brightRed: '#ffffff',
    brightGreen: '#ffffff',
    brightYellow: '#ffffff',
    brightBlue: '#eeeeee',
    brightMagenta: '#ffffff',
    brightCyan: '#ffffff',
    brightWhite: '#ffffff',
  },
};
