import type { Theme } from '../types';

export const monodark: Theme = {
  name: 'MonoDark',
  colors: {
    background: '#000000',
    surface: '#0a0a0a',
    border: '#333333',
    text: '#ffffff',
    textSecondary: '#999999',
    accent: '#ffffff',
    accentHover: '#cccccc',
    input: '#1a1a1a',
    inputBorder: '#444444',
    button: '#1a1a1a',
    buttonHover: '#2a2a2a',
    danger: '#ffffff',
    dangerHover: '#cccccc',
  },
  editor: {
    background: '#000000',
    foreground: '#ffffff',
    caret: '#ffffff',
    selection: '#333333',
    activeLine: '#1a1a1a',
    gutter: '#0a0a0a',
    gutterText: '#999999',
    activeLineGutter: '#1a1a1a',
    lineNumber: '#666666',
  },
  syntax: {
    keyword: '#ffffff',
    operator: '#ffffff',
    string: '#ffffff',
    number: '#ffffff',
    boolean: '#ffffff',
    comment: '#999999',
    function: '#ffffff',
    class: '#ffffff',
    variable: '#ffffff',
    property: '#ffffff',
    constant: '#ffffff',
    type: '#ffffff',
    tag: '#ffffff',
    attribute: '#ffffff',
  },
  ansi: {
    black: '#000000',
    red: '#ffffff',
    green: '#ffffff',
    yellow: '#ffffff',
    blue: '#ffffff',
    magenta: '#ffffff',
    cyan: '#ffffff',
    white: '#cccccc',
    brightBlack: '#666666',
    brightRed: '#ffffff',
    brightGreen: '#ffffff',
    brightYellow: '#ffffff',
    brightBlue: '#ffffff',
    brightMagenta: '#ffffff',
    brightCyan: '#ffffff',
    brightWhite: '#ffffff',
  },
};
