use super::{Word, WordCompile::*};

pub(super) const WORDS: &[Word] = &[
    Word {
        name: "dup",
        aliases: &[],
        category: "Stack",
        stack: "(a -- a a)",
        desc: "Duplicate top of stack",
        example: include_str!("../../../docs/cagire/examples/dup.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "dupn",
        aliases: &["!"],
        category: "Stack",
        stack: "(a n -- a a ... a)",
        desc: "Duplicate a onto stack n times",
        example: include_str!("../../../docs/cagire/examples/dupn.cagire"),
        compile: Simple,
        varargs: true,
    },
    Word {
        name: "drop",
        aliases: &[],
        category: "Stack",
        stack: "(a --)",
        desc: "Remove top of stack",
        example: include_str!("../../../docs/cagire/examples/drop.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "swap",
        aliases: &[],
        category: "Stack",
        stack: "(a b -- b a)",
        desc: "Exchange top two items",
        example: include_str!("../../../docs/cagire/examples/swap.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "over",
        aliases: &[],
        category: "Stack",
        stack: "(a b -- a b a)",
        desc: "Copy second to top",
        example: include_str!("../../../docs/cagire/examples/over.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "rot",
        aliases: &[],
        category: "Stack",
        stack: "(a b c -- b c a)",
        desc: "Rotate top three",
        example: include_str!("../../../docs/cagire/examples/rot.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "nip",
        aliases: &[],
        category: "Stack",
        stack: "(a b -- b)",
        desc: "Remove second item",
        example: include_str!("../../../docs/cagire/examples/nip.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "tuck",
        aliases: &[],
        category: "Stack",
        stack: "(a b -- b a b)",
        desc: "Copy top under second",
        example: include_str!("../../../docs/cagire/examples/tuck.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "2dup",
        aliases: &[],
        category: "Stack",
        stack: "(a b -- a b a b)",
        desc: "Duplicate top two values",
        example: include_str!("../../../docs/cagire/examples/2dup.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "2drop",
        aliases: &[],
        category: "Stack",
        stack: "(a b --)",
        desc: "Drop top two values",
        example: include_str!("../../../docs/cagire/examples/2drop.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "2swap",
        aliases: &[],
        category: "Stack",
        stack: "(a b c d -- c d a b)",
        desc: "Swap top two pairs",
        example: include_str!("../../../docs/cagire/examples/2swap.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "2over",
        aliases: &[],
        category: "Stack",
        stack: "(a b c d -- a b c d a b)",
        desc: "Copy second pair to top",
        example: include_str!("../../../docs/cagire/examples/2over.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "rev",
        aliases: &[],
        category: "Stack",
        stack: "(..n n -- ..n)",
        desc: "Reverse top n items",
        example: include_str!("../../../docs/cagire/examples/rev.cagire"),
        compile: Simple,
        varargs: true,
    },
    Word {
        name: "shuffle",
        aliases: &[],
        category: "Stack",
        stack: "(..n n -- ..n)",
        desc: "Randomly shuffle top n items",
        example: include_str!("../../../docs/cagire/examples/shuffle.cagire"),
        compile: Simple,
        varargs: true,
    },
    Word {
        name: "sort",
        aliases: &[],
        category: "Stack",
        stack: "(..n n -- ..n)",
        desc: "Sort top n items ascending",
        example: include_str!("../../../docs/cagire/examples/sort.cagire"),
        compile: Simple,
        varargs: true,
    },
    Word {
        name: "rsort",
        aliases: &[],
        category: "Stack",
        stack: "(..n n -- ..n)",
        desc: "Sort top n items descending",
        example: include_str!("../../../docs/cagire/examples/rsort.cagire"),
        compile: Simple,
        varargs: true,
    },
    Word {
        name: "sum",
        aliases: &[],
        category: "Stack",
        stack: "(..n n -- total)",
        desc: "Sum top n items",
        example: include_str!("../../../docs/cagire/examples/sum.cagire"),
        compile: Simple,
        varargs: true,
    },
    Word {
        name: "prod",
        aliases: &[],
        category: "Stack",
        stack: "(..n n -- product)",
        desc: "Multiply top n items",
        example: include_str!("../../../docs/cagire/examples/prod.cagire"),
        compile: Simple,
        varargs: true,
    },
    // Arithmetic
    Word {
        name: "+",
        aliases: &[],
        category: "Arithmetic",
        stack: "(a b -- a+b)",
        desc: "Add",
        example: include_str!("../../../docs/cagire/examples/plus.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "-",
        aliases: &[],
        category: "Arithmetic",
        stack: "(a b -- a-b)",
        desc: "Subtract",
        example: include_str!("../../../docs/cagire/examples/minus.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "*",
        aliases: &[],
        category: "Arithmetic",
        stack: "(a b -- a*b)",
        desc: "Multiply",
        example: include_str!("../../../docs/cagire/examples/star.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "/",
        aliases: &[],
        category: "Arithmetic",
        stack: "(a b -- a/b)",
        desc: "Divide",
        example: include_str!("../../../docs/cagire/examples/slash.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "mod",
        aliases: &[],
        category: "Arithmetic",
        stack: "(a b -- a%b)",
        desc: "Modulo",
        example: include_str!("../../../docs/cagire/examples/mod.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "neg",
        aliases: &[],
        category: "Arithmetic",
        stack: "(a -- -a)",
        desc: "Negate",
        example: include_str!("../../../docs/cagire/examples/neg.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "abs",
        aliases: &[],
        category: "Arithmetic",
        stack: "(a -- |a|)",
        desc: "Absolute value",
        example: include_str!("../../../docs/cagire/examples/abs.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "floor",
        aliases: &[],
        category: "Arithmetic",
        stack: "(f -- n)",
        desc: "Round down to integer",
        example: include_str!("../../../docs/cagire/examples/floor.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "ceil",
        aliases: &[],
        category: "Arithmetic",
        stack: "(f -- n)",
        desc: "Round up to integer",
        example: include_str!("../../../docs/cagire/examples/ceil.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "round",
        aliases: &[],
        category: "Arithmetic",
        stack: "(f -- n)",
        desc: "Round to nearest integer",
        example: include_str!("../../../docs/cagire/examples/round.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "min",
        aliases: &[],
        category: "Arithmetic",
        stack: "(a b -- min)",
        desc: "Minimum of two values",
        example: include_str!("../../../docs/cagire/examples/min.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "max",
        aliases: &[],
        category: "Arithmetic",
        stack: "(a b -- max)",
        desc: "Maximum of two values",
        example: include_str!("../../../docs/cagire/examples/max.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "pow",
        aliases: &[],
        category: "Arithmetic",
        stack: "(a b -- a^b)",
        desc: "Exponentiation",
        example: include_str!("../../../docs/cagire/examples/pow.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "sqrt",
        aliases: &[],
        category: "Arithmetic",
        stack: "(a -- √a)",
        desc: "Square root",
        example: include_str!("../../../docs/cagire/examples/sqrt.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "sin",
        aliases: &[],
        category: "Arithmetic",
        stack: "(a -- sin(a))",
        desc: "Sine (radians)",
        example: include_str!("../../../docs/cagire/examples/sin.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "cos",
        aliases: &[],
        category: "Arithmetic",
        stack: "(a -- cos(a))",
        desc: "Cosine (radians)",
        example: include_str!("../../../docs/cagire/examples/cos.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "log",
        aliases: &[],
        category: "Arithmetic",
        stack: "(a -- ln(a))",
        desc: "Natural logarithm",
        example: include_str!("../../../docs/cagire/examples/log.cagire"),
        compile: Simple,
        varargs: false,
    },
    // Comparison
    Word {
        name: "=",
        aliases: &[],
        category: "Comparison",
        stack: "(a b -- bool)",
        desc: "Equal",
        example: include_str!("../../../docs/cagire/examples/eq.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "!=",
        aliases: &["<>"],
        category: "Comparison",
        stack: "(a b -- bool)",
        desc: "Not equal",
        example: include_str!("../../../docs/cagire/examples/neq.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "lt",
        aliases: &[],
        category: "Comparison",
        stack: "(a b -- bool)",
        desc: "Less than",
        example: include_str!("../../../docs/cagire/examples/lt.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "gt",
        aliases: &[],
        category: "Comparison",
        stack: "(a b -- bool)",
        desc: "Greater than",
        example: include_str!("../../../docs/cagire/examples/gt.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "<=",
        aliases: &[],
        category: "Comparison",
        stack: "(a b -- bool)",
        desc: "Less or equal",
        example: include_str!("../../../docs/cagire/examples/lte.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: ">=",
        aliases: &[],
        category: "Comparison",
        stack: "(a b -- bool)",
        desc: "Greater or equal",
        example: include_str!("../../../docs/cagire/examples/gte.cagire"),
        compile: Simple,
        varargs: false,
    },
    // Logic
    Word {
        name: "and",
        aliases: &[],
        category: "Logic",
        stack: "(a b -- bool)",
        desc: "Logical and",
        example: include_str!("../../../docs/cagire/examples/and.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "or",
        aliases: &[],
        category: "Logic",
        stack: "(a b -- bool)",
        desc: "Logical or",
        example: include_str!("../../../docs/cagire/examples/or.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "not",
        aliases: &[],
        category: "Logic",
        stack: "(a -- bool)",
        desc: "Logical not",
        example: include_str!("../../../docs/cagire/examples/not.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "xor",
        aliases: &[],
        category: "Logic",
        stack: "(a b -- bool)",
        desc: "Exclusive or",
        example: include_str!("../../../docs/cagire/examples/xor.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "nand",
        aliases: &[],
        category: "Logic",
        stack: "(a b -- bool)",
        desc: "Not and",
        example: include_str!("../../../docs/cagire/examples/nand.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "nor",
        aliases: &[],
        category: "Logic",
        stack: "(a b -- bool)",
        desc: "Not or",
        example: include_str!("../../../docs/cagire/examples/nor.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "ifelse",
        aliases: &[],
        category: "Logic",
        stack: "(true-quot false-quot bool --)",
        desc: "Execute true-quot if true, else false-quot",
        example: include_str!("../../../docs/cagire/examples/ifelse.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "select",
        aliases: &[],
        category: "Logic",
        stack: "(..quots n --)",
        desc: "Execute nth quotation (0-indexed)",
        example: include_str!("../../../docs/cagire/examples/select.cagire"),
        compile: Simple,
        varargs: true,
    },
    Word {
        name: "?",
        aliases: &[],
        category: "Logic",
        stack: "(quot bool --)",
        desc: "Execute quotation if true",
        example: include_str!("../../../docs/cagire/examples/question.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "!?",
        aliases: &[],
        category: "Logic",
        stack: "(quot bool --)",
        desc: "Execute quotation if false",
        example: include_str!("../../../docs/cagire/examples/not_question.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "apply",
        aliases: &[],
        category: "Logic",
        stack: "(quot --)",
        desc: "Execute quotation unconditionally",
        example: include_str!("../../../docs/cagire/examples/apply.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "linmap",
        aliases: &[],
        category: "Arithmetic",
        stack: "(val inlo inhi outlo outhi -- mapped)",
        desc: "Linear map to output range",
        example: include_str!("../../../docs/cagire/examples/linmap.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "expmap",
        aliases: &[],
        category: "Arithmetic",
        stack: "(val lo hi -- mapped)",
        desc: "Exponential map (0-1 to range)",
        example: include_str!("../../../docs/cagire/examples/expmap.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "map",
        aliases: &[],
        category: "Logic",
        stack: "(.. quot --)",
        desc: "Apply quotation to each stack element",
        example: include_str!("../../../docs/cagire/examples/map.cagire"),
        compile: Simple,
        varargs: false,
    },
    // Control
    Word {
        name: "times",
        aliases: &[],
        category: "Control",
        stack: "(n quot --)",
        desc: "Execute quotation n times, @i holds current index",
        example: include_str!("../../../docs/cagire/examples/times.cagire"),
        compile: Simple,
        varargs: false,
    },
    // Variables
    Word {
        name: "@<var>",
        aliases: &[],
        category: "Variables",
        stack: "( -- val)",
        desc: "Fetch variable value",
        example: include_str!("../../../docs/cagire/examples/fetch_var.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "!<var>",
        aliases: &[],
        category: "Variables",
        stack: "(val --)",
        desc: "Store value in variable",
        example: include_str!("../../../docs/cagire/examples/store_var.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: ",<var>",
        aliases: &[],
        category: "Variables",
        stack: "(val -- val)",
        desc: "Store value in variable, keep on stack",
        example: include_str!("../../../docs/cagire/examples/peek_var.cagire"),
        compile: Simple,
        varargs: false,
    },
    // Definitions
    Word {
        name: ":",
        aliases: &[],
        category: "Definitions",
        stack: "( -- )",
        desc: "Begin word definition",
        example: include_str!("../../../docs/cagire/examples/colon.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: ";",
        aliases: &[],
        category: "Definitions",
        stack: "( -- )",
        desc: "End word definition",
        example: include_str!("../../../docs/cagire/examples/semicolon.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "forget",
        aliases: &[],
        category: "Definitions",
        stack: "(name --)",
        desc: "Remove user-defined word from dictionary",
        example: include_str!("../../../docs/cagire/examples/forget.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "++",
        aliases: &[],
        category: "String",
        stack: "(a b -- s)",
        desc: "Concatenate as string; numbers stringified",
        example: include_str!("../../../docs/cagire/examples/concat.cagire"),
        compile: Simple,
        varargs: false,
    },
];
