use super::{Word, WordCompile::*};

pub(super) const WORDS: &[Word] = &[
    // Envelope
    Word { name: "gain", aliases: &[], category: "Envelope", stack: "(v.. --)", desc: "Set volume (0-1)", example: include_str!("../../../docs/cagire/examples/gain.cagire"), compile: Param, varargs: true },
    Word { name: "postgain", aliases: &[], category: "Envelope", stack: "(v.. --)", desc: "Set post gain", example: include_str!("../../../docs/cagire/examples/postgain.cagire"), compile: Param, varargs: true },
    Word { name: "velocity", aliases: &["vel"], category: "Envelope", stack: "(v.. --)", desc: "Set velocity (0-1)", example: include_str!("../../../docs/cagire/examples/velocity.cagire"), compile: Param, varargs: true },
    Word { name: "attack", aliases: &["att", "a"], category: "Envelope", stack: "(v.. --)", desc: "Set attack time in seconds", example: include_str!("../../../docs/cagire/examples/attack.cagire"), compile: Param, varargs: true },
    Word { name: "decay", aliases: &["dec", "d"], category: "Envelope", stack: "(v.. --)", desc: "Set decay time in seconds", example: include_str!("../../../docs/cagire/examples/decay.cagire"), compile: Param, varargs: true },
    Word { name: "sustain", aliases: &["sus", "s"], category: "Envelope", stack: "(v.. --)", desc: "Set sustain level (0-1)", example: include_str!("../../../docs/cagire/examples/sustain.cagire"), compile: Param, varargs: true },
    Word { name: "release", aliases: &["rel", "r"], category: "Envelope", stack: "(v.. --)", desc: "Set release time in seconds", example: include_str!("../../../docs/cagire/examples/release.cagire"), compile: Param, varargs: true },
    Word { name: "envdelay", aliases: &["envdly"], category: "Envelope", stack: "(v.. --)", desc: "Set envelope delay time in seconds", example: include_str!("../../../docs/cagire/examples/envdelay.cagire"), compile: Param, varargs: true },
    Word { name: "hold", aliases: &["hld"], category: "Envelope", stack: "(v.. --)", desc: "Set envelope hold time in seconds", example: include_str!("../../../docs/cagire/examples/hold.cagire"), compile: Param, varargs: true },
    Word { name: "adsr", aliases: &[], category: "Envelope", stack: "(a d s r --)", desc: "Set attack, decay, sustain, release", example: include_str!("../../../docs/cagire/examples/adsr.cagire"), compile: Simple, varargs: false },
    Word { name: "ad", aliases: &[], category: "Envelope", stack: "(a d --)", desc: "Set attack, decay (sustain=0)", example: include_str!("../../../docs/cagire/examples/ad.cagire"), compile: Simple, varargs: false },
    // Filter
    Word { name: "lpf", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set lowpass frequency", example: include_str!("../../../docs/cagire/examples/lpf.cagire"), compile: Param, varargs: true },
    Word { name: "lpq", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set lowpass resonance", example: include_str!("../../../docs/cagire/examples/lpq.cagire"), compile: Param, varargs: true },
    Word { name: "hpf", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set highpass frequency", example: include_str!("../../../docs/cagire/examples/hpf.cagire"), compile: Param, varargs: true },
    Word { name: "hpq", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set highpass resonance", example: include_str!("../../../docs/cagire/examples/hpq.cagire"), compile: Param, varargs: true },
    Word { name: "bpf", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set bandpass frequency", example: include_str!("../../../docs/cagire/examples/bpf.cagire"), compile: Param, varargs: true },
    Word { name: "bpq", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set bandpass resonance", example: include_str!("../../../docs/cagire/examples/bpq.cagire"), compile: Param, varargs: true },
    Word { name: "llpf", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set ladder lowpass frequency", example: include_str!("../../../docs/cagire/examples/llpf.cagire"), compile: Param, varargs: true },
    Word { name: "llpq", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set ladder lowpass resonance", example: include_str!("../../../docs/cagire/examples/llpq.cagire"), compile: Param, varargs: true },
    Word { name: "lhpf", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set ladder highpass frequency", example: include_str!("../../../docs/cagire/examples/lhpf.cagire"), compile: Param, varargs: true },
    Word { name: "lhpq", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set ladder highpass resonance", example: include_str!("../../../docs/cagire/examples/lhpq.cagire"), compile: Param, varargs: true },
    Word { name: "lbpf", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set ladder bandpass frequency", example: include_str!("../../../docs/cagire/examples/lbpf.cagire"), compile: Param, varargs: true },
    Word { name: "lbpq", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set ladder bandpass resonance", example: include_str!("../../../docs/cagire/examples/lbpq.cagire"), compile: Param, varargs: true },
    Word { name: "ftype", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set filter type", example: include_str!("../../../docs/cagire/examples/ftype.cagire"), compile: Param, varargs: true },
    Word { name: "eqlo", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set low shelf gain (dB)", example: include_str!("../../../docs/cagire/examples/eqlo.cagire"), compile: Param, varargs: true },
    Word { name: "eqmid", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set mid peak gain (dB)", example: include_str!("../../../docs/cagire/examples/eqmid.cagire"), compile: Param, varargs: true },
    Word { name: "eqhi", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set high shelf gain (dB)", example: include_str!("../../../docs/cagire/examples/eqhi.cagire"), compile: Param, varargs: true },
    Word { name: "eqlofreq", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set low shelf frequency (Hz)", example: include_str!("../../../docs/cagire/examples/eqlofreq.cagire"), compile: Param, varargs: true },
    Word { name: "eqmidfreq", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set mid peak frequency (Hz)", example: include_str!("../../../docs/cagire/examples/eqmidfreq.cagire"), compile: Param, varargs: true },
    Word { name: "eqhifreq", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set high shelf frequency (Hz)", example: include_str!("../../../docs/cagire/examples/eqhifreq.cagire"), compile: Param, varargs: true },
    Word { name: "tilt", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set tilt EQ (-1 dark, 1 bright)", example: include_str!("../../../docs/cagire/examples/tilt.cagire"), compile: Param, varargs: true },
    Word { name: "comb", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set comb filter mix", example: include_str!("../../../docs/cagire/examples/comb.cagire"), compile: Param, varargs: true },
    Word { name: "combfreq", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set comb frequency", example: include_str!("../../../docs/cagire/examples/combfreq.cagire"), compile: Param, varargs: true },
    Word { name: "combfeedback", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set comb feedback", example: include_str!("../../../docs/cagire/examples/combfeedback.cagire"), compile: Param, varargs: true },
    Word { name: "combdamp", aliases: &[], category: "Filter", stack: "(v.. --)", desc: "Set comb damping", example: include_str!("../../../docs/cagire/examples/combdamp.cagire"), compile: Param, varargs: true },
    // Reverb
    Word { name: "verb", aliases: &[], category: "Reverb", stack: "(v.. --)", desc: "Set reverb mix", example: include_str!("../../../docs/cagire/examples/verb.cagire"), compile: Param, varargs: true },
    Word { name: "verbdecay", aliases: &[], category: "Reverb", stack: "(v.. --)", desc: "Set reverb decay (0-1)", example: include_str!("../../../docs/cagire/examples/verbdecay.cagire"), compile: Param, varargs: true },
    Word { name: "verbdamp", aliases: &[], category: "Reverb", stack: "(v.. --)", desc: "Set reverb damping", example: include_str!("../../../docs/cagire/examples/verbdamp.cagire"), compile: Param, varargs: true },
    Word { name: "verbpredelay", aliases: &[], category: "Reverb", stack: "(v.. --)", desc: "Set reverb predelay (0-1)", example: include_str!("../../../docs/cagire/examples/verbpredelay.cagire"), compile: Param, varargs: true },
    Word { name: "verbdiff", aliases: &[], category: "Reverb", stack: "(v.. --)", desc: "Set reverb diffusion", example: include_str!("../../../docs/cagire/examples/verbdiff.cagire"), compile: Param, varargs: true },
    Word { name: "verbtype", aliases: &[], category: "Reverb", stack: "(v.. --)", desc: "Set reverb algorithm (vital or dattorro)", example: include_str!("../../../docs/cagire/examples/verbtype.cagire"), compile: Param, varargs: true },
    Word { name: "verbchorus", aliases: &[], category: "Reverb", stack: "(v.. --)", desc: "Set reverb chorus amount (0-1)", example: include_str!("../../../docs/cagire/examples/verbchorus.cagire"), compile: Param, varargs: true },
    Word { name: "verbchorusfreq", aliases: &[], category: "Reverb", stack: "(v.. --)", desc: "Set reverb chorus frequency (0-1)", example: include_str!("../../../docs/cagire/examples/verbchorusfreq.cagire"), compile: Param, varargs: true },
    Word { name: "verbprelow", aliases: &[], category: "Reverb", stack: "(v.. --)", desc: "Set reverb pre-low filter (0-1)", example: include_str!("../../../docs/cagire/examples/verbprelow.cagire"), compile: Param, varargs: true },
    Word { name: "verbprehigh", aliases: &[], category: "Reverb", stack: "(v.. --)", desc: "Set reverb pre-high filter (0-1)", example: include_str!("../../../docs/cagire/examples/verbprehigh.cagire"), compile: Param, varargs: true },
    Word { name: "verblowcut", aliases: &[], category: "Reverb", stack: "(v.. --)", desc: "Set reverb low cut frequency (0-1)", example: include_str!("../../../docs/cagire/examples/verblowcut.cagire"), compile: Param, varargs: true },
    Word { name: "verbhighcut", aliases: &[], category: "Reverb", stack: "(v.. --)", desc: "Set reverb high cut frequency (0-1)", example: include_str!("../../../docs/cagire/examples/verbhighcut.cagire"), compile: Param, varargs: true },
    Word { name: "verblowgain", aliases: &[], category: "Reverb", stack: "(v.. --)", desc: "Set reverb low gain (0-1)", example: include_str!("../../../docs/cagire/examples/verblowgain.cagire"), compile: Param, varargs: true },
    Word { name: "size", aliases: &[], category: "Reverb", stack: "(v.. --)", desc: "Set size", example: include_str!("../../../docs/cagire/examples/size.cagire"), compile: Param, varargs: true },
    // Delay
    Word { name: "delay", aliases: &[], category: "Delay", stack: "(v.. --)", desc: "Set delay mix", example: include_str!("../../../docs/cagire/examples/delay.cagire"), compile: Param, varargs: true },
    Word { name: "delaytime", aliases: &[], category: "Delay", stack: "(v.. --)", desc: "Set delay time", example: include_str!("../../../docs/cagire/examples/delaytime.cagire"), compile: Param, varargs: true },
    Word { name: "delayfeedback", aliases: &[], category: "Delay", stack: "(v.. --)", desc: "Set delay feedback", example: include_str!("../../../docs/cagire/examples/delayfeedback.cagire"), compile: Param, varargs: true },
    Word { name: "delaytype", aliases: &[], category: "Delay", stack: "(v.. --)", desc: "Set delay type", example: include_str!("../../../docs/cagire/examples/delaytype.cagire"), compile: Param, varargs: true },
    // Lo-fi
    Word { name: "crush", aliases: &[], category: "Lo-fi", stack: "(v.. --)", desc: "Set bit crush", example: include_str!("../../../docs/cagire/examples/crush.cagire"), compile: Param, varargs: true },
    Word { name: "fold", aliases: &[], category: "Lo-fi", stack: "(v.. --)", desc: "Set wave fold", example: include_str!("../../../docs/cagire/examples/fold.cagire"), compile: Param, varargs: true },
    Word { name: "wrap", aliases: &[], category: "Lo-fi", stack: "(v.. --)", desc: "Set wave wrap", example: include_str!("../../../docs/cagire/examples/wrap.cagire"), compile: Param, varargs: true },
    Word { name: "distort", aliases: &[], category: "Lo-fi", stack: "(v.. --)", desc: "Set distortion", example: include_str!("../../../docs/cagire/examples/distort.cagire"), compile: Param, varargs: true },
    Word { name: "distortvol", aliases: &[], category: "Lo-fi", stack: "(v.. --)", desc: "Set distortion volume", example: include_str!("../../../docs/cagire/examples/distortvol.cagire"), compile: Param, varargs: true },
    // Stereo
    Word { name: "pan", aliases: &[], category: "Stereo", stack: "(v.. --)", desc: "Set pan (-1 to 1)", example: include_str!("../../../docs/cagire/examples/pan.cagire"), compile: Param, varargs: true },
    Word { name: "width", aliases: &[], category: "Stereo", stack: "(v.. --)", desc: "Set stereo width (0 mono, 1 normal, 2 wide)", example: include_str!("../../../docs/cagire/examples/width.cagire"), compile: Param, varargs: true },
    Word { name: "haas", aliases: &[], category: "Stereo", stack: "(v.. --)", desc: "Set Haas delay in ms (spatial placement)", example: include_str!("../../../docs/cagire/examples/haas.cagire"), compile: Param, varargs: true },
    // Mod FX
    Word { name: "phaser", aliases: &[], category: "Mod FX", stack: "(v.. --)", desc: "Set phaser rate", example: include_str!("../../../docs/cagire/examples/phaser.cagire"), compile: Param, varargs: true },
    Word { name: "phaserdepth", aliases: &[], category: "Mod FX", stack: "(v.. --)", desc: "Set phaser depth", example: include_str!("../../../docs/cagire/examples/phaserdepth.cagire"), compile: Param, varargs: true },
    Word { name: "phasersweep", aliases: &[], category: "Mod FX", stack: "(v.. --)", desc: "Set phaser sweep", example: include_str!("../../../docs/cagire/examples/phasersweep.cagire"), compile: Param, varargs: true },
    Word { name: "phasercenter", aliases: &[], category: "Mod FX", stack: "(v.. --)", desc: "Set phaser center", example: include_str!("../../../docs/cagire/examples/phasercenter.cagire"), compile: Param, varargs: true },
    Word { name: "flanger", aliases: &[], category: "Mod FX", stack: "(v.. --)", desc: "Set flanger rate", example: include_str!("../../../docs/cagire/examples/flanger.cagire"), compile: Param, varargs: true },
    Word { name: "flangerdepth", aliases: &[], category: "Mod FX", stack: "(v.. --)", desc: "Set flanger depth", example: include_str!("../../../docs/cagire/examples/flangerdepth.cagire"), compile: Param, varargs: true },
    Word { name: "flangerfeedback", aliases: &[], category: "Mod FX", stack: "(v.. --)", desc: "Set flanger feedback", example: include_str!("../../../docs/cagire/examples/flangerfeedback.cagire"), compile: Param, varargs: true },
    Word { name: "smear", aliases: &[], category: "Mod FX", stack: "(v.. --)", desc: "Set smear allpass chain mix (0 bypass, 1 full wet)", example: include_str!("../../../docs/cagire/examples/smear.cagire"), compile: Param, varargs: true },
    Word { name: "smearfreq", aliases: &[], category: "Mod FX", stack: "(v.. --)", desc: "Set smear allpass break frequency in Hz", example: include_str!("../../../docs/cagire/examples/smearfreq.cagire"), compile: Param, varargs: true },
    Word { name: "smearfb", aliases: &[], category: "Mod FX", stack: "(v.. --)", desc: "Set smear feedback for resonance (0-0.95)", example: include_str!("../../../docs/cagire/examples/smearfb.cagire"), compile: Param, varargs: true },
    Word { name: "chorus", aliases: &[], category: "Mod FX", stack: "(v.. --)", desc: "Set chorus rate", example: include_str!("../../../docs/cagire/examples/chorus.cagire"), compile: Param, varargs: true },
    Word { name: "chorusdepth", aliases: &[], category: "Mod FX", stack: "(v.. --)", desc: "Set chorus depth", example: include_str!("../../../docs/cagire/examples/chorusdepth.cagire"), compile: Param, varargs: true },
    Word { name: "chorusdelay", aliases: &[], category: "Mod FX", stack: "(v.. --)", desc: "Set chorus delay", example: include_str!("../../../docs/cagire/examples/chorusdelay.cagire"), compile: Param, varargs: true },
    Word { name: "feedback", aliases: &["fb"], category: "Mod FX", stack: "(v.. --)", desc: "Set feedback delay level", example: include_str!("../../../docs/cagire/examples/feedback.cagire"), compile: Param, varargs: true },
    Word { name: "fbtime", aliases: &["fbt"], category: "Mod FX", stack: "(v.. --)", desc: "Set feedback delay time in ms", example: include_str!("../../../docs/cagire/examples/fbtime.cagire"), compile: Param, varargs: true },
    Word { name: "fbdamp", aliases: &["fbd"], category: "Mod FX", stack: "(v.. --)", desc: "Set feedback delay damping", example: include_str!("../../../docs/cagire/examples/fbdamp.cagire"), compile: Param, varargs: true },
    Word { name: "fblfo", aliases: &[], category: "Mod FX", stack: "(v.. --)", desc: "Set feedback delay LFO rate in Hz", example: include_str!("../../../docs/cagire/examples/fblfo.cagire"), compile: Param, varargs: true },
    Word { name: "fblfodepth", aliases: &[], category: "Mod FX", stack: "(v.. --)", desc: "Set feedback delay LFO depth", example: include_str!("../../../docs/cagire/examples/fblfodepth.cagire"), compile: Param, varargs: true },
    Word { name: "fblfoshape", aliases: &[], category: "Mod FX", stack: "(v.. --)", desc: "Set feedback delay LFO shape", example: include_str!("../../../docs/cagire/examples/fblfoshape.cagire"), compile: Param, varargs: true },
    // Compressor
    Word { name: "comp", aliases: &[], category: "Compressor", stack: "(v.. --)", desc: "Set sidechain duck amount (0-1)", example: include_str!("../../../docs/cagire/examples/comp.cagire"), compile: Param, varargs: true },
    Word { name: "compattack", aliases: &["cattack"], category: "Compressor", stack: "(v.. --)", desc: "Set compressor attack time in seconds", example: include_str!("../../../docs/cagire/examples/compattack.cagire"), compile: Param, varargs: true },
    Word { name: "comprelease", aliases: &["crelease"], category: "Compressor", stack: "(v.. --)", desc: "Set compressor release time in seconds", example: include_str!("../../../docs/cagire/examples/comprelease.cagire"), compile: Param, varargs: true },
    Word { name: "comporbit", aliases: &["corbit"], category: "Compressor", stack: "(v.. --)", desc: "Set sidechain source orbit", example: include_str!("../../../docs/cagire/examples/comporbit.cagire"), compile: Param, varargs: true },
];
