use super::{Word, WordCompile::*};

pub(super) const WORDS: &[Word] = &[
    Word { name: "mtof", aliases: &[], category: "Music", stack: "(midi -- hz)", desc: "MIDI note to frequency", example: "69 mtof => 440.0", compile: Simple, varargs: false },
    Word { name: "ftom", aliases: &[], category: "Music", stack: "(hz -- midi)", desc: "Frequency to MIDI note", example: "440 ftom => 69.0", compile: Simple, varargs: false },
    Word { name: "maj", aliases: &[], category: "Chord", stack: "(root -- root third fifth)", desc: "Major triad", example: "c4 maj => 60 64 67", compile: Simple, varargs: true },
    Word { name: "m", aliases: &[], category: "Chord", stack: "(root -- root third fifth)", desc: "Minor triad", example: "c4 m => 60 63 67", compile: Simple, varargs: true },
    Word { name: "dim", aliases: &[], category: "Chord", stack: "(root -- root third fifth)", desc: "Diminished triad", example: "c4 dim => 60 63 66", compile: Simple, varargs: true },
    Word { name: "aug", aliases: &[], category: "Chord", stack: "(root -- root third fifth)", desc: "Augmented triad", example: "c4 aug => 60 64 68", compile: Simple, varargs: true },
    Word { name: "sus2", aliases: &[], category: "Chord", stack: "(root -- root second fifth)", desc: "Suspended 2nd", example: "c4 sus2 => 60 62 67", compile: Simple, varargs: true },
    Word { name: "sus4", aliases: &[], category: "Chord", stack: "(root -- root fourth fifth)", desc: "Suspended 4th", example: "c4 sus4 => 60 65 67", compile: Simple, varargs: true },
    Word { name: "maj7", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh)", desc: "Major 7th", example: "c4 maj7 => 60 64 67 71", compile: Simple, varargs: true },
    Word { name: "min7", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh)", desc: "Minor 7th", example: "c4 min7 => 60 63 67 70", compile: Simple, varargs: true },
    Word { name: "dom7", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh)", desc: "Dominant 7th", example: "c4 dom7 => 60 64 67 70", compile: Simple, varargs: true },
    Word { name: "dim7", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh)", desc: "Diminished 7th", example: "c4 dim7 => 60 63 66 69", compile: Simple, varargs: true },
    Word { name: "m7b5", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh)", desc: "Half-diminished (min7b5)", example: "c4 m7b5 => 60 63 66 70", compile: Simple, varargs: true },
    Word { name: "minmaj7", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh)", desc: "Minor-major 7th", example: "c4 minmaj7 => 60 63 67 71", compile: Simple, varargs: true },
    Word { name: "aug7", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh)", desc: "Augmented 7th", example: "c4 aug7 => 60 64 68 70", compile: Simple, varargs: true },
    Word { name: "maj6", aliases: &[], category: "Chord", stack: "(root -- root third fifth sixth)", desc: "Major 6th", example: "c4 maj6 => 60 64 67 69", compile: Simple, varargs: true },
    Word { name: "min6", aliases: &[], category: "Chord", stack: "(root -- root third fifth sixth)", desc: "Minor 6th", example: "c4 min6 => 60 63 67 69", compile: Simple, varargs: true },
    Word { name: "dom9", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh ninth)", desc: "Dominant 9th", example: "c4 dom9 => 60 64 67 70 74", compile: Simple, varargs: true },
    Word { name: "maj9", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh ninth)", desc: "Major 9th", example: "c4 maj9 => 60 64 67 71 74", compile: Simple, varargs: true },
    Word { name: "min9", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh ninth)", desc: "Minor 9th", example: "c4 min9 => 60 63 67 70 74", compile: Simple, varargs: true },
    Word { name: "dom11", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "Dominant 11th", example: "c4 dom11", compile: Simple, varargs: true },
    Word { name: "min11", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "Minor 11th", example: "c4 min11", compile: Simple, varargs: true },
    Word { name: "dom13", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "Dominant 13th", example: "c4 dom13", compile: Simple, varargs: true },
    Word { name: "add9", aliases: &[], category: "Chord", stack: "(root -- root third fifth ninth)", desc: "Major add 9", example: "c4 add9", compile: Simple, varargs: true },
    Word { name: "add11", aliases: &[], category: "Chord", stack: "(root -- root third fifth eleventh)", desc: "Major add 11", example: "c4 add11", compile: Simple, varargs: true },
    Word { name: "madd9", aliases: &[], category: "Chord", stack: "(root -- root third fifth ninth)", desc: "Minor add 9", example: "c4 madd9", compile: Simple, varargs: true },
    Word { name: "dom7b9", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "7th flat 9", example: "c4 dom7b9", compile: Simple, varargs: true },
    Word { name: "dom7s9", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "7th sharp 9 (Hendrix chord)", example: "c4 dom7s9", compile: Simple, varargs: true },
    Word { name: "dom7b5", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "7th flat 5", example: "c4 dom7b5", compile: Simple, varargs: true },
    Word { name: "dom7s5", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "7th sharp 5", example: "c4 dom7s5", compile: Simple, varargs: true },
];
