use super::{Word, WordCompile::*};

pub(super) const WORDS: &[Word] = &[
    Word { name: "mtof", aliases: &[], category: "Music", stack: "(midi -- hz)", desc: "MIDI note to frequency", example: include_str!("../../../docs/cagire/examples/mtof.cagire"), compile: Simple, varargs: false },
    Word { name: "ftom", aliases: &[], category: "Music", stack: "(hz -- midi)", desc: "Frequency to MIDI note", example: include_str!("../../../docs/cagire/examples/ftom.cagire"), compile: Simple, varargs: false },
    // Harmony
    Word { name: "key!", aliases: &[], category: "Harmony", stack: "(root --)", desc: "Set tonal center for scale operations", example: include_str!("../../../docs/cagire/examples/key_set.cagire"), compile: Simple, varargs: false },
    Word { name: "triad", aliases: &[], category: "Harmony", stack: "(degree -- n1 n2 n3)", desc: "Diatonic triad from scale degree (follows a scale word)", example: include_str!("../../../docs/cagire/examples/triad.cagire"), compile: Simple, varargs: true },
    Word { name: "seventh", aliases: &[], category: "Harmony", stack: "(degree -- n1 n2 n3 n4)", desc: "Diatonic seventh from scale degree (follows a scale word)", example: include_str!("../../../docs/cagire/examples/seventh.cagire"), compile: Simple, varargs: true },
    // Voicings
    Word { name: "inv", aliases: &[], category: "Chord", stack: "(a b c.. -- b c.. a+12)", desc: "Inversion: bottom note moves up an octave", example: include_str!("../../../docs/cagire/examples/inv.cagire"), compile: Simple, varargs: true },
    Word { name: "dinv", aliases: &[], category: "Chord", stack: "(a b.. z -- z-12 a b..)", desc: "Down inversion: top note moves down an octave", example: include_str!("../../../docs/cagire/examples/dinv.cagire"), compile: Simple, varargs: true },
    Word { name: "drop2", aliases: &[], category: "Chord", stack: "(a b c d -- b-12 a c d)", desc: "Drop-2 voicing", example: include_str!("../../../docs/cagire/examples/drop2.cagire"), compile: Simple, varargs: true },
    Word { name: "drop3", aliases: &[], category: "Chord", stack: "(a b c d -- c-12 a b d)", desc: "Drop-3 voicing", example: include_str!("../../../docs/cagire/examples/drop3.cagire"), compile: Simple, varargs: true },
    Word { name: "tp", aliases: &[], category: "Harmony", stack: "(n --)", desc: "Transpose all ints on stack by N semitones", example: include_str!("../../../docs/cagire/examples/tp.cagire"), compile: Simple, varargs: true },
    Word { name: "maj", aliases: &[], category: "Chord", stack: "(root -- root third fifth)", desc: "Major triad", example: include_str!("../../../docs/cagire/examples/maj.cagire"), compile: Simple, varargs: true },
    Word { name: "m", aliases: &[], category: "Chord", stack: "(root -- root third fifth)", desc: "Minor triad", example: include_str!("../../../docs/cagire/examples/m.cagire"), compile: Simple, varargs: true },
    Word { name: "dim", aliases: &[], category: "Chord", stack: "(root -- root third fifth)", desc: "Diminished triad", example: include_str!("../../../docs/cagire/examples/dim.cagire"), compile: Simple, varargs: true },
    Word { name: "aug", aliases: &[], category: "Chord", stack: "(root -- root third fifth)", desc: "Augmented triad", example: include_str!("../../../docs/cagire/examples/aug.cagire"), compile: Simple, varargs: true },
    Word { name: "sus2", aliases: &[], category: "Chord", stack: "(root -- root second fifth)", desc: "Suspended 2nd", example: include_str!("../../../docs/cagire/examples/sus2.cagire"), compile: Simple, varargs: true },
    Word { name: "sus4", aliases: &[], category: "Chord", stack: "(root -- root fourth fifth)", desc: "Suspended 4th", example: include_str!("../../../docs/cagire/examples/sus4.cagire"), compile: Simple, varargs: true },
    Word { name: "maj7", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh)", desc: "Major 7th", example: include_str!("../../../docs/cagire/examples/maj7.cagire"), compile: Simple, varargs: true },
    Word { name: "min7", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh)", desc: "Minor 7th", example: include_str!("../../../docs/cagire/examples/min7.cagire"), compile: Simple, varargs: true },
    Word { name: "dom7", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh)", desc: "Dominant 7th", example: include_str!("../../../docs/cagire/examples/dom7.cagire"), compile: Simple, varargs: true },
    Word { name: "dim7", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh)", desc: "Diminished 7th", example: include_str!("../../../docs/cagire/examples/dim7.cagire"), compile: Simple, varargs: true },
    Word { name: "m7b5", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh)", desc: "Half-diminished (min7b5)", example: include_str!("../../../docs/cagire/examples/m7b5.cagire"), compile: Simple, varargs: true },
    Word { name: "minmaj7", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh)", desc: "Minor-major 7th", example: include_str!("../../../docs/cagire/examples/minmaj7.cagire"), compile: Simple, varargs: true },
    Word { name: "aug7", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh)", desc: "Augmented 7th", example: include_str!("../../../docs/cagire/examples/aug7.cagire"), compile: Simple, varargs: true },
    Word { name: "maj6", aliases: &[], category: "Chord", stack: "(root -- root third fifth sixth)", desc: "Major 6th", example: include_str!("../../../docs/cagire/examples/maj6.cagire"), compile: Simple, varargs: true },
    Word { name: "min6", aliases: &[], category: "Chord", stack: "(root -- root third fifth sixth)", desc: "Minor 6th", example: include_str!("../../../docs/cagire/examples/min6.cagire"), compile: Simple, varargs: true },
    Word { name: "dom9", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh ninth)", desc: "Dominant 9th", example: include_str!("../../../docs/cagire/examples/dom9.cagire"), compile: Simple, varargs: true },
    Word { name: "maj9", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh ninth)", desc: "Major 9th", example: include_str!("../../../docs/cagire/examples/maj9.cagire"), compile: Simple, varargs: true },
    Word { name: "min9", aliases: &[], category: "Chord", stack: "(root -- root third fifth seventh ninth)", desc: "Minor 9th", example: include_str!("../../../docs/cagire/examples/min9.cagire"), compile: Simple, varargs: true },
    Word { name: "dom11", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "Dominant 11th", example: include_str!("../../../docs/cagire/examples/dom11.cagire"), compile: Simple, varargs: true },
    Word { name: "min11", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "Minor 11th", example: include_str!("../../../docs/cagire/examples/min11.cagire"), compile: Simple, varargs: true },
    Word { name: "dom13", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "Dominant 13th", example: include_str!("../../../docs/cagire/examples/dom13.cagire"), compile: Simple, varargs: true },
    Word { name: "add9", aliases: &[], category: "Chord", stack: "(root -- root third fifth ninth)", desc: "Major add 9", example: include_str!("../../../docs/cagire/examples/add9.cagire"), compile: Simple, varargs: true },
    Word { name: "add11", aliases: &[], category: "Chord", stack: "(root -- root third fifth eleventh)", desc: "Major add 11", example: include_str!("../../../docs/cagire/examples/add11.cagire"), compile: Simple, varargs: true },
    Word { name: "madd9", aliases: &[], category: "Chord", stack: "(root -- root third fifth ninth)", desc: "Minor add 9", example: include_str!("../../../docs/cagire/examples/madd9.cagire"), compile: Simple, varargs: true },
    Word { name: "dom7b9", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "7th flat 9", example: include_str!("../../../docs/cagire/examples/dom7b9.cagire"), compile: Simple, varargs: true },
    Word { name: "dom7s9", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "7th sharp 9 (Hendrix chord)", example: include_str!("../../../docs/cagire/examples/dom7s9.cagire"), compile: Simple, varargs: true },
    Word { name: "dom7b5", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "7th flat 5", example: include_str!("../../../docs/cagire/examples/dom7b5.cagire"), compile: Simple, varargs: true },
    Word { name: "dom7s5", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "7th sharp 5", example: include_str!("../../../docs/cagire/examples/dom7s5.cagire"), compile: Simple, varargs: true },
    Word { name: "pwr", aliases: &[], category: "Chord", stack: "(root -- root fifth)", desc: "Power chord", example: include_str!("../../../docs/cagire/examples/pwr.cagire"), compile: Simple, varargs: true },
    Word { name: "7sus4", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "Suspended 4th 7th", example: include_str!("../../../docs/cagire/examples/7sus4.cagire"), compile: Simple, varargs: true },
    Word { name: "9sus4", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "Suspended 4th 9th", example: include_str!("../../../docs/cagire/examples/9sus4.cagire"), compile: Simple, varargs: true },
    Word { name: "augmaj7", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "Augmented major 7th", example: include_str!("../../../docs/cagire/examples/augmaj7.cagire"), compile: Simple, varargs: true },
    Word { name: "maj69", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "Major 6/9", example: include_str!("../../../docs/cagire/examples/maj69.cagire"), compile: Simple, varargs: true },
    Word { name: "min69", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "Minor 6/9", example: include_str!("../../../docs/cagire/examples/min69.cagire"), compile: Simple, varargs: true },
    Word { name: "maj11", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "Major 11th", example: include_str!("../../../docs/cagire/examples/maj11.cagire"), compile: Simple, varargs: true },
    Word { name: "maj13", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "Major 13th", example: include_str!("../../../docs/cagire/examples/maj13.cagire"), compile: Simple, varargs: true },
    Word { name: "min13", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "Minor 13th", example: include_str!("../../../docs/cagire/examples/min13.cagire"), compile: Simple, varargs: true },
    Word { name: "dom7s11", aliases: &[], category: "Chord", stack: "(root -- ...)", desc: "Dominant 7th sharp 11", example: include_str!("../../../docs/cagire/examples/dom7s11.cagire"), compile: Simple, varargs: true },
];
