use super::{Word, WordCompile::*};

pub(super) const WORDS: &[Word] = &[
    // Probability
    Word {
        name: "rand",
        aliases: &[],
        category: "Probability",
        stack: "(min max -- n|f)",
        desc: "Random in range",
        example: include_str!("../../../docs/cagire/examples/rand.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "exprand",
        aliases: &[],
        category: "Probability",
        stack: "(lo hi -- f)",
        desc: "Exponential random biased toward lo",
        example: include_str!("../../../docs/cagire/examples/exprand.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "logrand",
        aliases: &[],
        category: "Probability",
        stack: "(lo hi -- f)",
        desc: "Exponential random biased toward hi",
        example: include_str!("../../../docs/cagire/examples/logrand.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "seed",
        aliases: &[],
        category: "Probability",
        stack: "(n --)",
        desc: "Set random seed",
        example: include_str!("../../../docs/cagire/examples/seed.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "coin",
        aliases: &[],
        category: "Probability",
        stack: "(-- bool)",
        desc: "50/50 random boolean",
        example: include_str!("../../../docs/cagire/examples/coin.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "chance",
        aliases: &[],
        category: "Probability",
        stack: "(quot prob --)",
        desc: "Execute quotation with probability (0.0-1.0)",
        example: include_str!("../../../docs/cagire/examples/chance.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "prob",
        aliases: &[],
        category: "Probability",
        stack: "(quot pct --)",
        desc: "Execute quotation with probability (0-100)",
        example: include_str!("../../../docs/cagire/examples/prob.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "choose",
        aliases: &[],
        category: "Probability",
        stack: "(..n n -- val)",
        desc: "Random pick from n items",
        example: include_str!("../../../docs/cagire/examples/choose.cagire"),
        compile: Simple,
        varargs: true,
    },
    Word {
        name: "cycle",
        aliases: &[],
        category: "Probability",
        stack: "(v1..vn n -- selected)",
        desc: "Cycle through n items by step runs",
        example: include_str!("../../../docs/cagire/examples/cycle.cagire"),
        compile: Simple,
        varargs: true,
    },
    Word {
        name: "pcycle",
        aliases: &[],
        category: "Probability",
        stack: "(v1..vn n -- selected)",
        desc: "Cycle through n items by pattern iteration",
        example: include_str!("../../../docs/cagire/examples/pcycle.cagire"),
        compile: Simple,
        varargs: true,
    },
    Word {
        name: "bounce",
        aliases: &[],
        category: "Probability",
        stack: "(v1..vn n -- selected)",
        desc: "Ping-pong cycle through n items",
        example: include_str!("../../../docs/cagire/examples/bounce.cagire"),
        compile: Simple,
        varargs: true,
    },
    Word {
        name: "pbounce",
        aliases: &[],
        category: "Probability",
        stack: "(v1..vn n -- selected)",
        desc: "Ping-pong cycle by pattern iteration",
        example: include_str!("../../../docs/cagire/examples/pbounce.cagire"),
        compile: Simple,
        varargs: true,
    },
    Word {
        name: "index",
        aliases: &[],
        category: "Probability",
        stack: "(v1..vn n idx -- selected)",
        desc: "Select item at explicit index",
        example: include_str!("../../../docs/cagire/examples/index.cagire"),
        compile: Simple,
        varargs: true,
    },
    Word {
        name: "wchoose",
        aliases: &[],
        category: "Probability",
        stack: "(v1 w1 v2 w2 ... n -- selected)",
        desc: "Weighted random pick",
        example: include_str!("../../../docs/cagire/examples/wchoose.cagire"),
        compile: Simple,
        varargs: true,
    },
    Word {
        name: "always",
        aliases: &[],
        category: "Probability",
        stack: "(quot --)",
        desc: "Always execute quotation",
        example: include_str!("../../../docs/cagire/examples/always.cagire"),
        compile: Probability(1.0),
        varargs: false,
    },
    Word {
        name: "never",
        aliases: &[],
        category: "Probability",
        stack: "(quot --)",
        desc: "Never execute quotation",
        example: include_str!("../../../docs/cagire/examples/never.cagire"),
        compile: Probability(0.0),
        varargs: false,
    },
    Word {
        name: "often",
        aliases: &[],
        category: "Probability",
        stack: "(quot --)",
        desc: "Execute quotation 75% of the time",
        example: include_str!("../../../docs/cagire/examples/often.cagire"),
        compile: Probability(0.75),
        varargs: false,
    },
    Word {
        name: "sometimes",
        aliases: &[],
        category: "Probability",
        stack: "(quot --)",
        desc: "Execute quotation 50% of the time",
        example: include_str!("../../../docs/cagire/examples/sometimes.cagire"),
        compile: Probability(0.5),
        varargs: false,
    },
    Word {
        name: "rarely",
        aliases: &[],
        category: "Probability",
        stack: "(quot --)",
        desc: "Execute quotation 25% of the time",
        example: include_str!("../../../docs/cagire/examples/rarely.cagire"),
        compile: Probability(0.25),
        varargs: false,
    },
    Word {
        name: "almostNever",
        aliases: &[],
        category: "Probability",
        stack: "(quot --)",
        desc: "Execute quotation 10% of the time",
        example: include_str!("../../../docs/cagire/examples/almostNever.cagire"),
        compile: Probability(0.1),
        varargs: false,
    },
    Word {
        name: "almostAlways",
        aliases: &[],
        category: "Probability",
        stack: "(quot --)",
        desc: "Execute quotation 90% of the time",
        example: include_str!("../../../docs/cagire/examples/almostAlways.cagire"),
        compile: Probability(0.9),
        varargs: false,
    },
    // Time
    Word {
        name: "every",
        aliases: &[],
        category: "Time",
        stack: "(quot n --)",
        desc: "Execute quotation every nth iteration",
        example: include_str!("../../../docs/cagire/examples/every.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "except",
        aliases: &[],
        category: "Time",
        stack: "(quot n --)",
        desc: "Execute quotation on all iterations except every nth",
        example: include_str!("../../../docs/cagire/examples/except.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "every+",
        aliases: &[],
        category: "Time",
        stack: "(quot n offset --)",
        desc: "Execute quotation every nth iteration with phase offset",
        example: include_str!("../../../docs/cagire/examples/every_plus.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "except+",
        aliases: &[],
        category: "Time",
        stack: "(quot n offset --)",
        desc: "Skip quotation every nth iteration with phase offset",
        example: include_str!("../../../docs/cagire/examples/except_plus.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "bjork",
        aliases: &[],
        category: "Time",
        stack: "(quot k n --)",
        desc: "Euclidean distribution over step runs",
        example: include_str!("../../../docs/cagire/examples/bjork.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "pbjork",
        aliases: &[],
        category: "Time",
        stack: "(quot k n --)",
        desc: "Euclidean distribution over pattern iterations",
        example: include_str!("../../../docs/cagire/examples/pbjork.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "first",
        aliases: &[],
        category: "Time",
        stack: "(quot n --)",
        desc: "Execute quotation only on the first n iterations",
        example: include_str!("../../../docs/cagire/examples/first.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "after",
        aliases: &[],
        category: "Time",
        stack: "(quot n --)",
        desc: "Execute quotation from iteration n onward",
        example: include_str!("../../../docs/cagire/examples/after.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "once",
        aliases: &[],
        category: "Time",
        stack: "(quot --)",
        desc: "Execute quotation only on iteration 0",
        example: include_str!("../../../docs/cagire/examples/once.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "loop",
        aliases: &[],
        category: "Time",
        stack: "(n --)",
        desc: "Fit sample to n beats",
        example: include_str!("../../../docs/cagire/examples/loop.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "tempo!",
        aliases: &[],
        category: "Time",
        stack: "(bpm --)",
        desc: "Set global tempo",
        example: include_str!("../../../docs/cagire/examples/tempo_set.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "speed!",
        aliases: &[],
        category: "Time",
        stack: "(multiplier --)",
        desc: "Set pattern speed multiplier",
        example: include_str!("../../../docs/cagire/examples/speed_set.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "at",
        aliases: &[],
        category: "Time",
        stack: "(v..n quot --)",
        desc: "Loop quotation per delta",
        example: include_str!("../../../docs/cagire/examples/at.cagire"),
        compile: Simple,
        varargs: true,
    },
    Word {
        name: "pat",
        aliases: &[],
        category: "Generator",
        stack: "(\"pattern\" -- f1 f2 ...)",
        desc:
            "Push pattern hit positions as floats. x=hit .=rest -=extend []=subdivide <|>=alternate",
        example: include_str!("../../../docs/cagire/examples/pat.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "prot",
        aliases: &[],
        category: "Generator",
        stack: "(\"pattern\" n -- \"pattern\")",
        desc: "Rotate pattern slots right by n (negative = left)",
        example: include_str!("../../../docs/cagire/examples/prot.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "prev",
        aliases: &[],
        category: "Generator",
        stack: "(\"pattern\" -- \"pattern\")",
        desc: "Reverse pattern slot order",
        example: include_str!("../../../docs/cagire/examples/prev.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "pinv",
        aliases: &[],
        category: "Generator",
        stack: "(\"pattern\" -- \"pattern\")",
        desc: "Invert pattern: hits become rests, rests become hits",
        example: include_str!("../../../docs/cagire/examples/pinv.cagire"),
        compile: Simple,
        varargs: false,
    },
    // Context
    Word {
        name: "step",
        aliases: &[],
        category: "Context",
        stack: "(-- n)",
        desc: "Current step index",
        example: include_str!("../../../docs/cagire/examples/step.cagire"),
        compile: Context("step"),
        varargs: false,
    },
    Word {
        name: "beat",
        aliases: &[],
        category: "Context",
        stack: "(-- f)",
        desc: "Current beat position",
        example: include_str!("../../../docs/cagire/examples/beat.cagire"),
        compile: Context("beat"),
        varargs: false,
    },
    Word {
        name: "pattern",
        aliases: &[],
        category: "Context",
        stack: "(-- n)",
        desc: "Current pattern index",
        example: include_str!("../../../docs/cagire/examples/pattern.cagire"),
        compile: Context("pattern"),
        varargs: false,
    },
    Word {
        name: "tempo",
        aliases: &[],
        category: "Context",
        stack: "(-- f)",
        desc: "Current BPM",
        example: include_str!("../../../docs/cagire/examples/tempo.cagire"),
        compile: Context("tempo"),
        varargs: false,
    },
    Word {
        name: "phase",
        aliases: &[],
        category: "Context",
        stack: "(-- f)",
        desc: "Phase in bar (0-1)",
        example: include_str!("../../../docs/cagire/examples/phase.cagire"),
        compile: Context("phase"),
        varargs: false,
    },
    Word {
        name: "slot",
        aliases: &[],
        category: "Context",
        stack: "(-- n)",
        desc: "Current slot number",
        example: include_str!("../../../docs/cagire/examples/slot.cagire"),
        compile: Context("slot"),
        varargs: false,
    },
    Word {
        name: "runs",
        aliases: &[],
        category: "Context",
        stack: "(-- n)",
        desc: "Times this step ran",
        example: include_str!("../../../docs/cagire/examples/runs.cagire"),
        compile: Context("runs"),
        varargs: false,
    },
    Word {
        name: "iter",
        aliases: &[],
        category: "Context",
        stack: "(-- n)",
        desc: "Pattern iteration count",
        example: include_str!("../../../docs/cagire/examples/iter.cagire"),
        compile: Context("iter"),
        varargs: false,
    },
    Word {
        name: "stepdur",
        aliases: &[],
        category: "Context",
        stack: "(-- f)",
        desc: "Step duration in seconds",
        example: include_str!("../../../docs/cagire/examples/stepdur.cagire"),
        compile: Context("stepdur"),
        varargs: false,
    },
    Word {
        name: "fill",
        aliases: &[],
        category: "Context",
        stack: "(-- bool)",
        desc: "Fill toggle (deferred, returns 0)",
        example: include_str!("../../../docs/cagire/examples/fill.cagire"),
        compile: Context("fill"),
        varargs: false,
    },
    // Generator
    Word {
        name: "..",
        aliases: &[],
        category: "Generator",
        stack: "(start end -- start start+1 ... end)",
        desc: "Arithmetic sequence",
        example: include_str!("../../../docs/cagire/examples/dotdot.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: ".,",
        aliases: &[],
        category: "Generator",
        stack: "(start end step -- start start+step ...)",
        desc: "Arithmetic sequence with custom step",
        example: include_str!("../../../docs/cagire/examples/dotcomma.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "gen",
        aliases: &[],
        category: "Generator",
        stack: "(quot n -- results...)",
        desc: "Execute quotation n times, push all results",
        example: include_str!("../../../docs/cagire/examples/gen.cagire"),
        compile: Simple,
        varargs: true,
    },
    Word {
        name: "geom..",
        aliases: &[],
        category: "Generator",
        stack: "(start ratio count -- ...)",
        desc: "Geometric sequence",
        example: include_str!("../../../docs/cagire/examples/geom_seq.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "euclid",
        aliases: &[],
        category: "Generator",
        stack: "(k n -- f1 f2 ... fk)",
        desc: "Euclidean rhythm as normalized positions (0.0-1.0)",
        example: include_str!("../../../docs/cagire/examples/euclid.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "euclidrot",
        aliases: &[],
        category: "Generator",
        stack: "(k n r -- f1 f2 ... fk)",
        desc: "Euclidean rhythm as normalized positions with rotation",
        example: include_str!("../../../docs/cagire/examples/euclidrot.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "div",
        aliases: &[],
        category: "Generator",
        stack: "(n -- f1 f2 ... fn)",
        desc: "Equal subdivision positions (0.0 to 1.0)",
        example: include_str!("../../../docs/cagire/examples/div.cagire"),
        compile: Simple,
        varargs: false,
    },
    Word {
        name: "swing",
        aliases: &[],
        category: "Generator",
        stack: "(n ratio -- f1 f2 ... fn)",
        desc: "Subdivision with swing (ratio 0.5 = straight)",
        example: include_str!("../../../docs/cagire/examples/swing.cagire"),
        compile: Simple,
        varargs: false,
    },
    // Scene
    Word {
        name: "exe",
        aliases: &[],
        category: "Scene",
        stack: "(line frame --)",
        desc: "Execute a script at given line and frame",
        example: include_str!("../../../docs/cagire/examples/exe.cagire"),
        compile: Simple,
        varargs: false,
    },
    // Debug
    Word {
        name: "print",
        aliases: &[],
        category: "Debug",
        stack: "(v --)",
        desc: "Print top of stack to log",
        example: include_str!("../../../docs/cagire/examples/print.cagire"),
        compile: Simple,
        varargs: false,
    },
];
