use super::{Word, WordCompile::*};

pub(super) const WORDS: &[Word] = &[
    // Probability
    Word { name: "rand", aliases: &[], category: "Probability", stack: "(min max -- n|f)", desc: "Random in range", example: "1 6 rand", compile: Simple, varargs: false },
    Word { name: "exprand", aliases: &[], category: "Probability", stack: "(lo hi -- f)", desc: "Exponential random biased toward lo", example: "1.0 100.0 exprand", compile: Simple, varargs: false },
    Word { name: "logrand", aliases: &[], category: "Probability", stack: "(lo hi -- f)", desc: "Exponential random biased toward hi", example: "1.0 100.0 logrand", compile: Simple, varargs: false },
    Word { name: "seed", aliases: &[], category: "Probability", stack: "(n --)", desc: "Set random seed", example: "12345 seed", compile: Simple, varargs: false },
    Word { name: "coin", aliases: &[], category: "Probability", stack: "(-- bool)", desc: "50/50 random boolean", example: "coin", compile: Simple, varargs: false },
    Word { name: "chance", aliases: &[], category: "Probability", stack: "(quot prob --)", desc: "Execute quotation with probability (0.0-1.0)", example: "( 2 distort ) 0.75 chance", compile: Simple, varargs: false },
    Word { name: "prob", aliases: &[], category: "Probability", stack: "(quot pct --)", desc: "Execute quotation with probability (0-100)", example: "( 2 distort ) 75 prob", compile: Simple, varargs: false },
    Word { name: "choose", aliases: &[], category: "Probability", stack: "(..n n -- val)", desc: "Random pick from n items", example: "1 2 3 3 choose", compile: Simple, varargs: true },
    Word { name: "cycle", aliases: &[], category: "Probability", stack: "(v1..vn n -- selected)", desc: "Cycle through n items by step runs", example: "60 64 67 3 cycle", compile: Simple, varargs: true },
    Word { name: "pcycle", aliases: &[], category: "Probability", stack: "(v1..vn n -- selected)", desc: "Cycle through n items by pattern iteration", example: "60 64 67 3 pcycle", compile: Simple, varargs: true },
    Word { name: "bounce", aliases: &[], category: "Probability", stack: "(v1..vn n -- selected)", desc: "Ping-pong cycle through n items", example: "60 64 67 72 4 bounce", compile: Simple, varargs: true },
    Word { name: "pbounce", aliases: &[], category: "Probability", stack: "(v1..vn n -- selected)", desc: "Ping-pong cycle by pattern iteration", example: "60 64 67 72 4 pbounce", compile: Simple, varargs: true },
    Word { name: "index", aliases: &[], category: "Probability", stack: "(v1..vn n idx -- selected)", desc: "Select item at explicit index", example: "60 64 67 3 1 index", compile: Simple, varargs: true },
    Word { name: "wchoose", aliases: &[], category: "Probability", stack: "(v1 w1 v2 w2 ... n -- selected)", desc: "Weighted random pick", example: "60 0.6 64 0.3 67 0.1 3 wchoose", compile: Simple, varargs: true },
    Word { name: "always", aliases: &[], category: "Probability", stack: "(quot --)", desc: "Always execute quotation", example: "( 2 distort ) always", compile: Probability(1.0), varargs: false },
    Word { name: "never", aliases: &[], category: "Probability", stack: "(quot --)", desc: "Never execute quotation", example: "( 2 distort ) never", compile: Probability(0.0), varargs: false },
    Word { name: "often", aliases: &[], category: "Probability", stack: "(quot --)", desc: "Execute quotation 75% of the time", example: "( 2 distort ) often", compile: Probability(0.75), varargs: false },
    Word { name: "sometimes", aliases: &[], category: "Probability", stack: "(quot --)", desc: "Execute quotation 50% of the time", example: "( 2 distort ) sometimes", compile: Probability(0.5), varargs: false },
    Word { name: "rarely", aliases: &[], category: "Probability", stack: "(quot --)", desc: "Execute quotation 25% of the time", example: "( 2 distort ) rarely", compile: Probability(0.25), varargs: false },
    Word { name: "almostNever", aliases: &[], category: "Probability", stack: "(quot --)", desc: "Execute quotation 10% of the time", example: "( 2 distort ) almostNever", compile: Probability(0.1), varargs: false },
    Word { name: "almostAlways", aliases: &[], category: "Probability", stack: "(quot --)", desc: "Execute quotation 90% of the time", example: "( 2 distort ) almostAlways", compile: Probability(0.9), varargs: false },
    // Time
    Word { name: "every", aliases: &[], category: "Time", stack: "(quot n --)", desc: "Execute quotation every nth iteration", example: "( 2 distort ) 4 every", compile: Simple, varargs: false },
    Word { name: "except", aliases: &[], category: "Time", stack: "(quot n --)", desc: "Execute quotation on all iterations except every nth", example: "( 2 distort ) 4 except", compile: Simple, varargs: false },
    Word { name: "every+", aliases: &[], category: "Time", stack: "(quot n offset --)", desc: "Execute quotation every nth iteration with phase offset", example: "( snare ) 4 2 every+", compile: Simple, varargs: false },
    Word { name: "except+", aliases: &[], category: "Time", stack: "(quot n offset --)", desc: "Skip quotation every nth iteration with phase offset", example: "( snare ) 4 2 except+", compile: Simple, varargs: false },
    Word { name: "bjork", aliases: &[], category: "Time", stack: "(quot k n --)", desc: "Euclidean distribution over step runs", example: "( 2 distort ) 3 8 bjork", compile: Simple, varargs: false },
    Word { name: "pbjork", aliases: &[], category: "Time", stack: "(quot k n --)", desc: "Euclidean distribution over pattern iterations", example: "( 2 distort ) 3 8 pbjork", compile: Simple, varargs: false },
    Word { name: "loop", aliases: &[], category: "Time", stack: "(n --)", desc: "Fit sample to n beats", example: "\"break\" snd 4 loop .", compile: Simple, varargs: false },
    Word { name: "tempo!", aliases: &[], category: "Time", stack: "(bpm --)", desc: "Set global tempo", example: "140 tempo!", compile: Simple, varargs: false },
    Word { name: "speed!", aliases: &[], category: "Time", stack: "(multiplier --)", desc: "Set pattern speed multiplier", example: "2.0 speed!", compile: Simple, varargs: false },
    Word { name: "at", aliases: &[], category: "Time", stack: "(v1..vn --)", desc: "Set delta context for emit timing", example: "0 0.5 at \"kick\" snd .", compile: Simple, varargs: true },
    // Context
    Word { name: "step", aliases: &[], category: "Context", stack: "(-- n)", desc: "Current step index", example: "step", compile: Context("step"), varargs: false },
    Word { name: "beat", aliases: &[], category: "Context", stack: "(-- f)", desc: "Current beat position", example: "beat", compile: Context("beat"), varargs: false },
    Word { name: "pattern", aliases: &[], category: "Context", stack: "(-- n)", desc: "Current pattern index", example: "pattern", compile: Context("pattern"), varargs: false },
    Word { name: "pbank", aliases: &[], category: "Context", stack: "(-- n)", desc: "Current pattern bank index (deferred)", example: "pbank", compile: Context("bank"), varargs: false },
    Word { name: "tempo", aliases: &[], category: "Context", stack: "(-- f)", desc: "Current BPM", example: "tempo", compile: Context("tempo"), varargs: false },
    Word { name: "phase", aliases: &[], category: "Context", stack: "(-- f)", desc: "Phase in bar (0-1)", example: "phase", compile: Context("phase"), varargs: false },
    Word { name: "slot", aliases: &[], category: "Context", stack: "(-- n)", desc: "Current slot number", example: "slot", compile: Context("slot"), varargs: false },
    Word { name: "runs", aliases: &[], category: "Context", stack: "(-- n)", desc: "Times this step ran", example: "runs", compile: Context("runs"), varargs: false },
    Word { name: "iter", aliases: &[], category: "Context", stack: "(-- n)", desc: "Pattern iteration count", example: "iter", compile: Context("iter"), varargs: false },
    Word { name: "stepdur", aliases: &[], category: "Context", stack: "(-- f)", desc: "Step duration in seconds", example: "stepdur", compile: Context("stepdur"), varargs: false },
    Word { name: "fill", aliases: &[], category: "Context", stack: "(-- bool)", desc: "Fill toggle (deferred, returns 0)", example: "fill", compile: Context("fill"), varargs: false },
    // Generator
    Word { name: "..", aliases: &[], category: "Generator", stack: "(start end -- start start+1 ... end)", desc: "Arithmetic sequence", example: "1 4 ..", compile: Simple, varargs: false },
    Word { name: ".,", aliases: &[], category: "Generator", stack: "(start end step -- start start+step ...)", desc: "Arithmetic sequence with custom step", example: "0 1 0.25 .,", compile: Simple, varargs: false },
    Word { name: "gen", aliases: &[], category: "Generator", stack: "(quot n -- results...)", desc: "Execute quotation n times, push all results", example: "( 1 6 rand ) 4 gen", compile: Simple, varargs: true },
    Word { name: "geom..", aliases: &[], category: "Generator", stack: "(start ratio count -- ...)", desc: "Geometric sequence", example: "1 2 4 geom..", compile: Simple, varargs: false },
    Word { name: "euclid", aliases: &[], category: "Generator", stack: "(k n -- i1 i2 ... ik)", desc: "Euclidean rhythm indices", example: "4 8 euclid", compile: Simple, varargs: false },
    Word { name: "euclidrot", aliases: &[], category: "Generator", stack: "(k n r -- i1 i2 ... ik)", desc: "Euclidean rhythm indices with rotation", example: "3 8 2 euclidrot", compile: Simple, varargs: false },
    // Debug
    Word { name: "print", aliases: &[], category: "Debug", stack: "(v --)", desc: "Print top of stack to log", example: "42 print", compile: Simple, varargs: false },
];
