use super::{Word, WordCompile::*};

pub(super) const WORDS: &[Word] = &[
    // Sound
    Word { name: "sound", aliases: &["snd"], category: "Sound", stack: "(name --)", desc: "Begin sound command", example: include_str!("../../../docs/cagire/examples/sound.cagire"), compile: Simple, varargs: false },
    Word { name: ".", aliases: &[], category: "Sound", stack: "(--)", desc: "Emit current sound", example: include_str!("../../../docs/cagire/examples/dot.cagire"), compile: Simple, varargs: false },
    Word { name: "clear", aliases: &[], category: "Sound", stack: "(--)", desc: "Clear sound register", example: include_str!("../../../docs/cagire/examples/clear.cagire"), compile: Simple, varargs: false },
    Word { name: "all", aliases: &[], category: "Sound", stack: "(--)", desc: "Apply current params to all sounds", example: include_str!("../../../docs/cagire/examples/all.cagire"), compile: Simple, varargs: false },
    Word { name: "noall", aliases: &[], category: "Sound", stack: "(--)", desc: "Clear global params", example: include_str!("../../../docs/cagire/examples/noall.cagire"), compile: Simple, varargs: false },
    Word { name: "rec", aliases: &[], category: "Sound", stack: "(name --)", desc: "Toggle recording audio output to named sample", example: include_str!("../../../docs/cagire/examples/rec.cagire"), compile: Simple, varargs: false },
    Word { name: "overdub", aliases: &["dub"], category: "Sound", stack: "(name --)", desc: "Toggle overdub recording", example: include_str!("../../../docs/cagire/examples/overdub.cagire"), compile: Simple, varargs: false },
    Word { name: "orec", aliases: &[], category: "Sound", stack: "(name orbit --)", desc: "Toggle recording a single orbit", example: include_str!("../../../docs/cagire/examples/orec.cagire"), compile: Simple, varargs: false },
    Word { name: "odub", aliases: &[], category: "Sound", stack: "(name orbit --)", desc: "Toggle overdub recording a single orbit", example: include_str!("../../../docs/cagire/examples/odub.cagire"), compile: Simple, varargs: false },
    // Sample
    Word { name: "bank", aliases: &[], category: "Sample", stack: "(v.. --)", desc: "Select sample variant: appends suffix to sample name (e.g. kick + \"b\" → kick_b)", example: include_str!("../../../docs/cagire/examples/bank.cagire"), compile: Param, varargs: true },
    Word { name: "time", aliases: &[], category: "Sample", stack: "(v.. --)", desc: "Set time offset", example: include_str!("../../../docs/cagire/examples/time.cagire"), compile: Param, varargs: true },
    Word { name: "gate", aliases: &[], category: "Sample", stack: "(v.. --)", desc: "Set gate duration (total note length, 0 = infinite sustain)", example: include_str!("../../../docs/cagire/examples/gate.cagire"), compile: Param, varargs: true },
    Word { name: "speed", aliases: &[], category: "Sample", stack: "(v.. --)", desc: "Set playback speed", example: include_str!("../../../docs/cagire/examples/speed.cagire"), compile: Param, varargs: true },
    Word { name: "begin", aliases: &[], category: "Sample", stack: "(v.. --)", desc: "Set sample start (0-1)", example: include_str!("../../../docs/cagire/examples/begin.cagire"), compile: Param, varargs: true },
    Word { name: "end", aliases: &[], category: "Sample", stack: "(v.. --)", desc: "Set sample end (0-1)", example: include_str!("../../../docs/cagire/examples/end.cagire"), compile: Param, varargs: true },
    Word { name: "voice", aliases: &[], category: "Sample", stack: "(v.. --)", desc: "Set voice number", example: include_str!("../../../docs/cagire/examples/voice.cagire"), compile: Param, varargs: true },
    Word { name: "orbit", aliases: &[], category: "Sample", stack: "(v.. --)", desc: "Set orbit/bus", example: include_str!("../../../docs/cagire/examples/orbit.cagire"), compile: Param, varargs: true },
    Word { name: "n", aliases: &[], category: "Sample", stack: "(v.. --)", desc: "Set sample number", example: include_str!("../../../docs/cagire/examples/n.cagire"), compile: Param, varargs: true },
    Word { name: "inchan", aliases: &[], category: "Sample", stack: "(v.. --)", desc: "Select input channel for live input (0-indexed)", example: include_str!("../../../docs/cagire/examples/inchan.cagire"), compile: Param, varargs: true },
    Word { name: "cut", aliases: &[], category: "Sample", stack: "(v.. --)", desc: "Set cut group", example: include_str!("../../../docs/cagire/examples/cut.cagire"), compile: Param, varargs: true },
    Word { name: "reset", aliases: &[], category: "Sample", stack: "(v.. --)", desc: "Reset parameter", example: include_str!("../../../docs/cagire/examples/reset.cagire"), compile: Param, varargs: true },
    Word { name: "stretch", aliases: &[], category: "Sample", stack: "(v.. --)", desc: "Time stretch factor (pitch-independent)", example: include_str!("../../../docs/cagire/examples/stretch.cagire"), compile: Param, varargs: true },
    Word { name: "slice", aliases: &[], category: "Sample", stack: "(v.. --)", desc: "Divide sample into N equal slices", example: include_str!("../../../docs/cagire/examples/slice.cagire"), compile: Param, varargs: true },
    Word { name: "pick", aliases: &[], category: "Sample", stack: "(v.. --)", desc: "Select which slice to play (0-indexed, wraps)", example: include_str!("../../../docs/cagire/examples/pick.cagire"), compile: Param, varargs: true },
    Word { name: "partials", aliases: &[], category: "Oscillator", stack: "(v.. --)", desc: "Set number of active harmonics (add source only)", example: include_str!("../../../docs/cagire/examples/partials.cagire"), compile: Param, varargs: true },
    // Oscillator
    Word { name: "freq", aliases: &[], category: "Oscillator", stack: "(v.. --)", desc: "Set frequency (Hz)", example: include_str!("../../../docs/cagire/examples/freq.cagire"), compile: Param, varargs: true },
    Word { name: "detune", aliases: &[], category: "Oscillator", stack: "(v.. --)", desc: "Set detune amount", example: include_str!("../../../docs/cagire/examples/detune.cagire"), compile: Param, varargs: true },
    Word { name: "pw", aliases: &[], category: "Oscillator", stack: "(v.. --)", desc: "Set pulse width", example: include_str!("../../../docs/cagire/examples/pw.cagire"), compile: Param, varargs: true },
    Word { name: "spread", aliases: &[], category: "Oscillator", stack: "(v.. --)", desc: "Set stereo spread", example: include_str!("../../../docs/cagire/examples/spread.cagire"), compile: Param, varargs: true },
    Word { name: "mult", aliases: &[], category: "Oscillator", stack: "(v.. --)", desc: "Set multiplier", example: include_str!("../../../docs/cagire/examples/mult.cagire"), compile: Param, varargs: true },
    Word { name: "warp", aliases: &[], category: "Oscillator", stack: "(v.. --)", desc: "Set warp amount", example: include_str!("../../../docs/cagire/examples/warp.cagire"), compile: Param, varargs: true },
    Word { name: "mirror", aliases: &[], category: "Oscillator", stack: "(v.. --)", desc: "Set mirror", example: include_str!("../../../docs/cagire/examples/mirror.cagire"), compile: Param, varargs: true },
    Word { name: "harmonics", aliases: &[], category: "Oscillator", stack: "(v.. --)", desc: "Set harmonics", example: include_str!("../../../docs/cagire/examples/harmonics.cagire"), compile: Param, varargs: true },
    Word { name: "timbre", aliases: &[], category: "Oscillator", stack: "(v.. --)", desc: "Set timbre", example: include_str!("../../../docs/cagire/examples/timbre.cagire"), compile: Param, varargs: true },
    Word { name: "morph", aliases: &[], category: "Oscillator", stack: "(v.. --)", desc: "Set morph", example: include_str!("../../../docs/cagire/examples/morph.cagire"), compile: Param, varargs: true },
    Word { name: "coarse", aliases: &[], category: "Oscillator", stack: "(v.. --)", desc: "Set coarse tune", example: include_str!("../../../docs/cagire/examples/coarse.cagire"), compile: Param, varargs: true },
    Word { name: "sub", aliases: &[], category: "Oscillator", stack: "(v.. --)", desc: "Set sub oscillator level", example: include_str!("../../../docs/cagire/examples/sub.cagire"), compile: Param, varargs: true },
    Word { name: "suboct", aliases: &[], category: "Oscillator", stack: "(v.. --)", desc: "Set sub oscillator octave", example: include_str!("../../../docs/cagire/examples/suboct.cagire"), compile: Param, varargs: true },
    Word { name: "subwave", aliases: &[], category: "Oscillator", stack: "(v.. --)", desc: "Set sub oscillator waveform", example: include_str!("../../../docs/cagire/examples/subwave.cagire"), compile: Param, varargs: true },
    Word { name: "wave", aliases: &["waveform"], category: "Oscillator", stack: "(v.. --)", desc: "Set oscillator waveform", example: include_str!("../../../docs/cagire/examples/wave.cagire"), compile: Param, varargs: true },
    Word { name: "note", aliases: &[], category: "Oscillator", stack: "(v.. --)", desc: "Set MIDI note", example: include_str!("../../../docs/cagire/examples/note.cagire"), compile: Param, varargs: true },
    // Wavetable
    Word { name: "scan", aliases: &[], category: "Wavetable", stack: "(v.. --)", desc: "Set wavetable scan position", example: include_str!("../../../docs/cagire/examples/scan.cagire"), compile: Param, varargs: true },
    Word { name: "wtlen", aliases: &[], category: "Wavetable", stack: "(v.. --)", desc: "Set wavetable cycle length", example: include_str!("../../../docs/cagire/examples/wtlen.cagire"), compile: Param, varargs: true },
    // FM
    Word { name: "fm", aliases: &[], category: "FM", stack: "(v.. --)", desc: "Set FM frequency", example: include_str!("../../../docs/cagire/examples/fm.cagire"), compile: Param, varargs: true },
    Word { name: "fmh", aliases: &[], category: "FM", stack: "(v.. --)", desc: "Set FM harmonic ratio", example: include_str!("../../../docs/cagire/examples/fmh.cagire"), compile: Param, varargs: true },
    Word { name: "fmshape", aliases: &[], category: "FM", stack: "(v.. --)", desc: "Set FM shape", example: include_str!("../../../docs/cagire/examples/fmshape.cagire"), compile: Param, varargs: true },
    Word { name: "fm2", aliases: &[], category: "FM", stack: "(v.. --)", desc: "Set FM operator 2 depth", example: include_str!("../../../docs/cagire/examples/fm2.cagire"), compile: Param, varargs: true },
    Word { name: "fm2h", aliases: &[], category: "FM", stack: "(v.. --)", desc: "Set FM operator 2 harmonic ratio", example: include_str!("../../../docs/cagire/examples/fm2h.cagire"), compile: Param, varargs: true },
    Word { name: "fmalgo", aliases: &[], category: "FM", stack: "(v.. --)", desc: "Set FM algorithm", example: include_str!("../../../docs/cagire/examples/fmalgo.cagire"), compile: Param, varargs: true },
    Word { name: "fmfb", aliases: &[], category: "FM", stack: "(v.. --)", desc: "Set FM feedback amount", example: include_str!("../../../docs/cagire/examples/fmfb.cagire"), compile: Param, varargs: true },
    // Modulation
    Word { name: "vib", aliases: &[], category: "Modulation", stack: "(v.. --)", desc: "Set vibrato rate", example: include_str!("../../../docs/cagire/examples/vib.cagire"), compile: Param, varargs: true },
    Word { name: "vibmod", aliases: &[], category: "Modulation", stack: "(v.. --)", desc: "Set vibrato depth", example: include_str!("../../../docs/cagire/examples/vibmod.cagire"), compile: Param, varargs: true },
    Word { name: "vibshape", aliases: &[], category: "Modulation", stack: "(v.. --)", desc: "Set vibrato shape", example: include_str!("../../../docs/cagire/examples/vibshape.cagire"), compile: Param, varargs: true },
    Word { name: "am", aliases: &[], category: "Modulation", stack: "(v.. --)", desc: "Set AM frequency", example: include_str!("../../../docs/cagire/examples/am.cagire"), compile: Param, varargs: true },
    Word { name: "amdepth", aliases: &[], category: "Modulation", stack: "(v.. --)", desc: "Set AM depth", example: include_str!("../../../docs/cagire/examples/amdepth.cagire"), compile: Param, varargs: true },
    Word { name: "amshape", aliases: &[], category: "Modulation", stack: "(v.. --)", desc: "Set AM shape", example: include_str!("../../../docs/cagire/examples/amshape.cagire"), compile: Param, varargs: true },
    Word { name: "rm", aliases: &[], category: "Modulation", stack: "(v.. --)", desc: "Set RM frequency", example: include_str!("../../../docs/cagire/examples/rm.cagire"), compile: Param, varargs: true },
    Word { name: "rmdepth", aliases: &[], category: "Modulation", stack: "(v.. --)", desc: "Set RM depth", example: include_str!("../../../docs/cagire/examples/rmdepth.cagire"), compile: Param, varargs: true },
    Word { name: "rmshape", aliases: &[], category: "Modulation", stack: "(v.. --)", desc: "Set RM shape", example: include_str!("../../../docs/cagire/examples/rmshape.cagire"), compile: Param, varargs: true },
    // LFO
    Word { name: "ramp", aliases: &[], category: "LFO", stack: "(freq curve -- val)", desc: "Ramp [0,1]", example: include_str!("../../../docs/cagire/examples/ramp.cagire"), compile: Simple, varargs: false },
    Word { name: "range", aliases: &[], category: "LFO", stack: "(val min max -- scaled)", desc: "Scale [0,1] to [min,max]", example: include_str!("../../../docs/cagire/examples/range.cagire"), compile: Simple, varargs: false },
    Word { name: "linramp", aliases: &[], category: "LFO", stack: "(freq -- val)", desc: "Linear ramp (curve=1)", example: include_str!("../../../docs/cagire/examples/linramp.cagire"), compile: Simple, varargs: false },
    Word { name: "expramp", aliases: &[], category: "LFO", stack: "(freq -- val)", desc: "Exponential ramp (curve=3)", example: include_str!("../../../docs/cagire/examples/expramp.cagire"), compile: Simple, varargs: false },
    Word { name: "logramp", aliases: &[], category: "LFO", stack: "(freq -- val)", desc: "Logarithmic ramp (curve=0.3)", example: include_str!("../../../docs/cagire/examples/logramp.cagire"), compile: Simple, varargs: false },
    Word { name: "triangle", aliases: &[], category: "LFO", stack: "(freq -- val)", desc: "Triangle wave [0,1]", example: include_str!("../../../docs/cagire/examples/triangle.cagire"), compile: Simple, varargs: false },
    Word { name: "perlin", aliases: &[], category: "LFO", stack: "(freq -- val)", desc: "Perlin noise [0,1]", example: include_str!("../../../docs/cagire/examples/perlin.cagire"), compile: Simple, varargs: false },
    // Audio-rate Modulation DSL
    Word { name: "lfo", aliases: &[], category: "Audio Modulation", stack: "(min max period -- str)", desc: "Sine oscillation", example: include_str!("../../../docs/cagire/examples/lfo.cagire"), compile: Simple, varargs: false },
    Word { name: "tlfo", aliases: &[], category: "Audio Modulation", stack: "(min max period -- str)", desc: "Triangle oscillation", example: include_str!("../../../docs/cagire/examples/tlfo.cagire"), compile: Simple, varargs: false },
    Word { name: "wlfo", aliases: &[], category: "Audio Modulation", stack: "(min max period -- str)", desc: "Sawtooth oscillation", example: include_str!("../../../docs/cagire/examples/wlfo.cagire"), compile: Simple, varargs: false },
    Word { name: "qlfo", aliases: &[], category: "Audio Modulation", stack: "(min max period -- str)", desc: "Square oscillation", example: include_str!("../../../docs/cagire/examples/qlfo.cagire"), compile: Simple, varargs: false },
    Word { name: "slide", aliases: &[], category: "Audio Modulation", stack: "(start end dur -- str)", desc: "Linear transition", example: include_str!("../../../docs/cagire/examples/slide.cagire"), compile: Simple, varargs: false },
    Word { name: "expslide", aliases: &[], category: "Audio Modulation", stack: "(start end dur -- str)", desc: "Exponential transition", example: include_str!("../../../docs/cagire/examples/expslide.cagire"), compile: Simple, varargs: false },
    Word { name: "sslide", aliases: &[], category: "Audio Modulation", stack: "(start end dur -- str)", desc: "Smooth transition", example: include_str!("../../../docs/cagire/examples/sslide.cagire"), compile: Simple, varargs: false },
    Word { name: "islide", aliases: &[], category: "Audio Modulation", stack: "(start end dur -- str)", desc: "Swell transition (slow start, fast finish)", example: include_str!("../../../docs/cagire/examples/islide.cagire"), compile: Simple, varargs: false },
    Word { name: "oslide", aliases: &[], category: "Audio Modulation", stack: "(start end dur -- str)", desc: "Pluck transition (fast attack, slow settle)", example: include_str!("../../../docs/cagire/examples/oslide.cagire"), compile: Simple, varargs: false },
    Word { name: "pslide", aliases: &[], category: "Audio Modulation", stack: "(start end dur -- str)", desc: "Stair transition (8 discrete steps)", example: include_str!("../../../docs/cagire/examples/pslide.cagire"), compile: Simple, varargs: false },
    Word { name: "jit", aliases: &[], category: "Audio Modulation", stack: "(min max period -- str)", desc: "Random hold", example: include_str!("../../../docs/cagire/examples/jit.cagire"), compile: Simple, varargs: false },
    Word { name: "sjit", aliases: &[], category: "Audio Modulation", stack: "(min max period -- str)", desc: "Smooth random", example: include_str!("../../../docs/cagire/examples/sjit.cagire"), compile: Simple, varargs: false },
    Word { name: "drunk", aliases: &[], category: "Audio Modulation", stack: "(min max period -- str)", desc: "Drunk walk", example: include_str!("../../../docs/cagire/examples/drunk.cagire"), compile: Simple, varargs: false },
    Word { name: "ead", aliases: &[], category: "Audio Modulation", stack: "(min max a d -- str)", desc: "Percussive envelope mod: min^max:a:d:0:0", example: include_str!("../../../docs/cagire/examples/ead.cagire"), compile: Simple, varargs: false },
    Word { name: "eadr", aliases: &[], category: "Audio Modulation", stack: "(min max a d r -- str)", desc: "Percussive envelope mod with release: min^max:a:d:0:r", example: include_str!("../../../docs/cagire/examples/eadr.cagire"), compile: Simple, varargs: false },
    Word { name: "eadsr", aliases: &[], category: "Audio Modulation", stack: "(min max a d s r -- str)", desc: "ADSR envelope mod: min^max:a:d:s:r", example: include_str!("../../../docs/cagire/examples/eadsr.cagire"), compile: Simple, varargs: false },
    Word { name: "env", aliases: &[], category: "Audio Modulation", stack: "(min max a d s r -- str)", desc: "DAHDSR envelope modulation: min^max:a:d:s:r", example: include_str!("../../../docs/cagire/examples/env.cagire"), compile: Simple, varargs: false },
    Word { name: "lpg", aliases: &[], category: "Audio Modulation", stack: "(min max depth --)", desc: "Low pass gate: pairs amp envelope with lpf modulation", example: include_str!("../../../docs/cagire/examples/lpg.cagire"), compile: Simple, varargs: false },
];
